### ISSUE TITLE
Voice command stops working after initial boot

### ISSUE THREAD

**Issue by awernick** [gartnera/headunit#1]
When using the steering wheel voice button, the Google Voice command should activate.
This functionality only works on the first use of Android Auto. All consecutive uses will default back to the Mazda Voice Command functionality.

This issue is can be resolved by setting enable_input_filter in `/tmp/mnt/data` to 2. Setting the file to 1 will only work once, since the original developer intended it use as test to prevent bricks. Setting a value of 2 makes the voice command interception persist after a reboot.

AA version: 091b

**Comment by gartnera** [comment]
USB installer to perform tweak posted here: https://github.com/gartnera/headunit/releases/download/v0.91B/AndroidAuto_ButtonPatch.zip
