### ISSUE TITLE
Waze and How to install latest release

### ISSUE THREAD

**Issue by felipecorrea9** [gartnera/headunit#102]
Hi, 

Is the latest realease compatible with Waze?

How can I install the latest release (1.04)?  

Thanks!

**Comment by Trevelopment** [comment]
Hi Waze is compatible and you can install the latest release here: https://github.com/gartnera/headunit/releases/download/v1.04/AndroidAuto_v1.04.zip
or even more up to date releases here:
http://aa.mazdatweaks.win  <-- v1.06
http"//aabeta.mazdatweaks.win <-- v1.07

**Comment by felipecorrea9** [comment]
What changed between  1.04 and 1.07?

Thanks!!

**Comment by Trevelopment** [comment]
1.05 - video focus issues fixed when making/receiving bluetooth calls
1.06 - sound issues resolved & GPS issues half resolved
1.07 - GPS code rewritten to be more stable and integrate with MZD navigation & control USB audio when it has focus also switch to MZD music with FAV (⭐️)  button

**Comment by iainheng** [comment]
I am using ver 1.04 via your AIO installer. Can I install the new version 1.07 directly without uninstalling 1.04 first? Also will I be able to uninstall AA with AIO in the future?

Sorry for my noob question. 😣

**Comment by Trevelopment** [comment]
yes and yes
