### ISSUE TITLE
Android Auto does not recognize pho e

### ISSUE THREAD

**Issue by felipecorrea9** [gartnera/headunit#103]
Hi,

I just installed version 1.04, but when I run it on the car it gets stuck at the AA startup.
Message waiting for device.My device is a Galaxy S8 Plus connected via USB and Bluetooth.

Any ideas?
thanks,
Best reagrds

**Comment by felipecorrea9** [comment]
![20171127_191010](https://user-images.githubusercontent.com/11468516/33292194-12d83922-d3a7-11e7-9cc5-b8c2c5c8aebf.jpg)

**Comment by Trevelopment** [comment]
Your phone tries to connect so try this: at the point when you see that message try putting your phone into mtp or ptp mode.

**Comment by felipecorrea9** [comment]
Solved. _it was my damaged cable. For some reason it only worked for charging but did not work for data transfer.

**Comment by mishan** [comment]
That's because USB is 4 wires. 2 for power, 2 for data. It happens.On Nov 29, 2017 04:24, felipecorrea9 <notifications@github.com> wrote:Solved. _it was my damaged cable. For some reason it only worked for charging but did not work for data transfer.
