### ISSUE TITLE
Continuous Integration Support

### ISSUE THREAD

**Issue by Syquel** [gartnera/headunit#104]
I think it would be nice to have Continuous Integration support to make releases easier and maybe open the door for code quality tools in the future ;)

Therefore I commited a very simple / naive approach to my fork: https://github.com/Syquel/headunit/commit/aa7aa314933423611e4dc092e7b2753fef603f16

Travis CI is triggered on every push and for tags a new GitHub Release is automatically created.
Here is my example:
https://travis-ci.org/Syquel/headunit/builds/308878786
https://github.com/Syquel/headunit/releases/tag/v1.05-alpha-0

This approach is by far not perfect (but I do not know when I will find time to improve the build process), but could at least be a starting point for someone.
Suggestions:

- Create Makefile in top-level folder and delegate to Makefiles in sub-folders
- Separation of source files and build artifacts (and separation of compilation and deployment artifacts) into different folders
  - Move sources to "src" folder
  - Move build artifacts to "out" or "build" folder (maybe take a look into the build architecture of Lineage OS)
- Integration of code quality services like [SonarCloud](https://sonarcloud.io) or [Coverity Scan](https://scan.coverity.com/)
- Separation of tooling (m3-toolchain etc) from source
  - Move sources to "src" folder
  - Move additional tooling to "contrib" folder

Those are just some thoughts / suggestions which might help in the long term.
If I find time over the Christmas Holidays I will try to do some things myself.

Feel free to use the commit to build something better :)

**Comment by lmagder** [comment]
Interesting, I didn't know there was free CI on travis-ci like that! Thanks for looking into this. Everything you're suggesting is totally reasonable, but to be honest I'm a developer by day also, so when I get home to do hobby stuff ensuring we have robust, repeatable builds is not really at the top of my "fun" list despite it being really useful, so I've been lazy... :smile:

That said though, if you're up for doing this cleanup I'm definitely willing to consider a PR. I think what you have so far is a pretty good bang for the buck for just a few changes, so I might set that up in the meantime after I poke around a bit in Travis.

**Comment by Trevelopment** [comment]
I am using Gitlab CI in a mirror of this repo 
https://gitlab.com/Trezdog44/headunit
https://gitlab.com/Trezdog44/headunit/blob/master/.gitlab-ci.yml
