### ISSUE TITLE
Android Auto Error

### ISSUE THREAD

**Issue by hanisacsouka** [gartnera/headunit#106]
Hello, I installed Android Auto using AIO 2.7 on Mazda 3 Connect V 56.00.100 but when I start it I receive the below errors:

failed to load plugin '/usr/lib/gstreamer-0.10/libmfw_gst_mpeg2dec.so': lib_mpeg2_dec_arm11_elinux.so.2.2.0: cannot open shared object file: no such file or directory

I uninstalled and reinstalled several times but same issue

Please check below photos

https://drive.google.com/file/d/1z9Mr5knyZEKtzc7VO5kbB_a6t8FhzlPL/view?usp=sharing
https://drive.google.com/file/d/1gtke7brAM1nDDfjPLKESgOTiUJjfXPAD/view?usp=sharing
https://drive.google.com/file/d/1VW9wyrwpBhxEHYpDgGqHUx2hC5DwJ2l5/view?usp=sharing

Thanks

**Comment by Trevelopment** [comment]
you will always get those errors everyone does and they happen because of the version of gstreamer running on the CMU not Android Auto itself.

**Comment by hanisacsouka** [comment]
So what is the solution?

**Comment by mishaaq** [comment]
@hanisacsouka this error has no impact on the AA behaviour nor the CMU itself. You can just ignore it.

**Comment by hanisacsouka** [comment]
@mishaaq but it doesn't start, it freezes on this screen forever

**Comment by mishaaq** [comment]
@hanisacsouka not related to these errors, must be something different. What version of Android Auto you have installed on the phone?

**Comment by hanisacsouka** [comment]
Latest version, but this error happen when I start AA from the Car Touch Screen

**Comment by Trevelopment** [comment]
so what kind of phone are you using? and if you say iphone then gtfo
