### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by hanisacsouka** [gartnera/headunit#107]
What CMU version is supported with Android Auto?

**Comment by Trevelopment** [comment]
v55 - v59 all subversions are supported only pre v55 are not supported

**Comment by hanisacsouka** [comment]
I tried v56 and I had an error and you said because of the version!

**Comment by Trevelopment** [comment]
no I said that particular error was thrown by an old version of gstreamer but they dont impact AA at all. Let me ask you this, what kind of phone are you using?
