### ISSUE TITLE
Add more AMPs to USB port

### ISSUE THREAD

**Issue by felipecorrea9** [gartnera/headunit#108]
Is it possible to add more AMPs programmatically to usb ports?
Since AA makes the phone consume more battery and since Mazda cars only have 0.5 amps, the charging is almost equal as no charging at all.
I read somewhere that when it detects that the plugged phone is an iPhone it sends an additional 0.5 amp so it ends up with 1. No idea why it does not work for Android Phones

It would be awesome to be able to charge while using AA.

**Comment by mkeith83** [comment]
@felipecorrea9 Unfortunately not. It is part of the USB spec. If data is being transferred it can only supply .5 amps power per the usb2 spec, which I believe these ports are using. I'm not familiar with the iphone charging but this is probably due to it being a different cable.
