### ISSUE TITLE
GPS stopped working after installing AA .93A

### ISSUE THREAD

**Issue by katsuya82** [gartnera/headunit#11]
Hi,

I've successfully installed AA and worked on my Australian Mazda CX5 56.00.513. However, the original navigation system is now not getting any GPS data. I've tried uninstalling AA and still not working. I have not yet tried factory rest as I afraid I might end up in boot loop. 

Has anyone experience similar issue and any work around for it?

NOTE. THERE IS NO OTHER TWICKS EVER INSTALLED ON MY CX-5

Regards,

Katsuya

**Comment by esenaksoy** [comment]
Hi, that happened to me as well. I hope you haven't factory reseted already, cause I did, and I bricked the unit. They had to replace it. Fortunately my car has a warranty and since they couldn't find what really happened I didn't had to pay anything.

My unit version was: 56.00.230 EU Mazda3

**Comment by amkeric** [comment]
Hi. Did you manage to fix your issue?

I have the new CX-5 with 59.00.449 EU. I am facing the same issue, navigation system does not get any GPS data after I connect my phone and Android Auto app starts in the CMU. However, in my case the GPS data is restored after I just unplug the phone and Android Auto app stops.

**Comment by Trevelopment** [comment]
When Android Auto is using the GPS channel, GPS data from the CMU cannot be processed simultaneously.  There is no way to make the Android Auto app on the phone use the GPS data from the CMU so... This may be an unfixable issue... Also unplugging your phone fixes the issue because you free up the channel.
