### ISSUE TITLE
Pixel 2 XL Not Detected

### ISSUE THREAD

**Issue by Borillion** [gartnera/headunit#112]
My Pixel 2 XL is not detected when connected. 
OS Version 8.1.0
Android Auto Version 2.8.574514-release

How can I help gather more information to assist in debugging this issue?

**Comment by Trevelopment** [comment]
OK first some troubleshooting
1. Try different cables.  This just happened to me where one of my USB cables stopped working for no apparent reason.
2. Tap the textbox in the credits screen to see the headunit.log and check the last entries will probably say something like Nothing found, waiting.  You can also SSH in and get the file at 
/tmp/mnt/data/headunit.log.  You can also check it with AIO Tweaks app if you have it.
3. I get emailed about this approximately once a week and 9 times out of 10 its just the USB cable Pixel 2XL should work perfectly

**Comment by Borillion** [comment]
I know you closed this but I tried different cables same thing. It seems to regularly happen when there are incoming notifications. Have not been able to pin more down than that. I know the android app runs some kind of server to the head-unit are the ways to debug or collect logs on the AA side of things?

**Comment by Trevelopment** [comment]
So you say 
>  It seems to regularly happen when there are incoming notifications. 
Does that mean that your phone is detected because you have gotten it to connect to AA in your car? Because this issue says that you phone is not detected but what it sounds like you're saying is that is disconnects intermittently which is a different thing.
