### ISSUE TITLE
Smartphone does not connect

### ISSUE THREAD

**Issue by catalinvasile92** [gartnera/headunit#116]
Mazda Connect connects successfully through bluetooth to my Lenovo Vibe Shot, but the phone does not get detected inside Android Auto headunit app.

Worth mentioning: I have the 59.00.504 firmware

If I turn the knob, some debug info is printed in the Android Auto app (pictures attached).
![img_20171227_233903](https://user-images.githubusercontent.com/1883886/34394308-fbd06f66-eb60-11e7-987c-bfceb8e29391.jpg)

![img_20171227_233851](https://user-images.githubusercontent.com/1883886/34394307-fbb1d042-eb60-11e7-9e3b-d799e933730f.jpg)

**Comment by Trevelopment** [comment]
How many different USB cables have you tried?

**Comment by catalinvasile92** [comment]
I've tried with multiple cables. The phone is charging, but nothing more.

**Comment by catalinvasile92** [comment]
Yep, you were right. It was the cable. I can't believe this is an actual problem. I thought it was headunit specific problem, so didn't actually search for Android Auto general problems. Sorry for opening this useless topic.

I would still let this issue here, and not delete, so you don't run in dumb asses like me again.

This cable did the thing for me:  Anker PowerLine+ Nylon 1,8 m

**Comment by Trevelopment** [comment]
Exactly once a week for about a year now I usually get it in a email where someone has the exact same issue and 100% pf the time its the cable or they just don know they need to connect a USB cable at all that is why I was so confident to tell you that without hesitation and you know what is funny almost every person also says "its not the cable my phone is charging just fine"
