### ISSUE TITLE
Don't hear "system" messages listening to radio

### ISSUE THREAD

**Issue by mishaaq** [gartnera/headunit#119]
Another issue regarding audio focus. I like listening to radio when driving, but I don't hear some of the AA "messages" in this case. For example incoming calls. I can notice that someone is calling only by the message appearing on top of the screen. When I pick up everything is OK.

**Comment by lmagder** [comment]
Is it just incoming phone calls or everything? It seems like everything works for me so it's hard to debug. Logs are helpful since I think we log a lot of the audio events, both from AA and from CMU so it might pin-point the exact sequence of events that's causing the issue.

**Comment by mishaaq** [comment]
Might still exists, but after moving to Nexus 5X I cannot reproduce the issue anymore and just close it.
