### ISSUE TITLE
Error Message When Starting App

### ISSUE THREAD

**Issue by JeffWeim** [gartnera/headunit#124]
Hi,

When I open the Android Auto (AA) application it is stuck on the initial loading screen. When I then tap the screen to view the logs, the last line is always displaying: `W:/home/mazda/headunit/hu/hu_usb-cpp:466:Start: Nothing found, waiting`

The mobile device I am using is a Google Pixel 2 connected to my car via Bluetooth. 

I've also attempted several AIO-TI installs/uninstalls of AA but I am still getting this error/message.

Any troubleshooting tips or guidance would be much appreciated.

Jeff

**Comment by JeffWeim** [comment]
Closing, since I guess (For the Google Pixel 2 at least) your device must be connected via USB

**Comment by wipwar** [comment]
You are correct. USB is needed at this stage.

**Comment by ETx13** [comment]
Hey I have this exact same problem but I am connected via USB. My phone charges but doesn't detect that it's connected to USB. Any ideas?

**Comment by Trevelopment** [comment]
@ETx13 only high quality USB cables will work for AA.  Low quality cables will still charge your phone but will not connect to AA.  
Solution: Try better USB cables

**Comment by ETx13** [comment]
That worked! Had to steal the GFs LG charging cord but replaced it with my longer charging cord muahaha Thanks!
