### ISSUE TITLE
Lost focus when calling someone using Google Assistant

### ISSUE THREAD

**Issue by tomcontr** [gartnera/headunit#126]
I installed latest version 1.08v downloaded from MazdaTweaks, and Im still having this issue. Also sometimes when someone is calling me and I answere it loses focus too, so then I have to go to the main menu (Mazda Menu) and relaunch Android Auto.

**Comment by iainheng** [comment]
Me too having the same issue. But it only occurs in the first call. Subsequent calls are fine and stay in AA properly.

**Comment by mishan** [comment]
I've had this happen as well. This seems to be caused by all sorts of things. Sometimes it's a call, sometimes I've even had Google Maps talk and cause this. It's not consistently reproducible with Maps. If it's consistently reproducible with calls, it may be easier to track down then.

**Comment by mishan** [comment]
Oh, and FM radio (which I often listen to)  stays muted. I usually just pull the USB out of my phone and plug it back in and it works.
