### ISSUE TITLE
Once exit back to the main screen, it won't relaunch

### ISSUE THREAD

**Issue by waynesi** [gartnera/headunit#129]
Hi,

I'm using v1.08 installed via the All in One Tweak. The AA launches fine 100% when the car starts. However, if I quit the app to the main screen, I can no longer relaunch the AA from the Applications. I got the following errors shown on the screen. I don't know how to extra the log, so took some
![img_1582](https://user-images.githubusercontent.com/1307286/39086641-c71e08a6-458c-11e8-8528-ab847d7567a0.JPG)
![img_1583](https://user-images.githubusercontent.com/1307286/39086642-c7535c4a-458c-11e8-9bc8-a63e0e858102.JPG)
![img_1584](https://user-images.githubusercontent.com/1307286/39086643-c76ab408-458c-11e8-9933-0c3e5486a2a1.JPG)

Please help. Thanks.

Also great appreciation to your wonderful work.

**Comment by Trevelopment** [comment]
the only part of the log we need to see it the last lines all the way at the bottom... you didnt quite make it there

**Comment by waynesi** [comment]
Hi,
Sorry, my bad! I've redone the photos. The pictures are attached in the order from bottom scrolling to the top.

The exact symptom was, the AA started fine to begin with. Then I used the Exit to Mazda Connect menu item or Home hardware button to quit to the home screen. After I relaunch the AA from the Applications menu, I got this copyright screen with blank log area and then the screen went black after 1 or 2 seconds. Although the screen stayed black, the Okay Google voice command was responding, but I couldn't use Open Google Maps voice command to force the screen to refresh. Press the Home hardware button again, I was given the copyright screen. Quite often the log area was blank. I had to tap on screen or quit to Home Screen and relaunch AA to get something there.

A few screens at the bottom of the log are shown below. For full log please download from  https://www.dropbox.com/s/9gmxctoqc81vujb/MazdaAA.zip

![img_1595](https://user-images.githubusercontent.com/1307286/39093680-593bd95a-461b-11e8-86c5-34c9b787740a.JPG)
![img_1596](https://user-images.githubusercontent.com/1307286/39093681-5952d178-461b-11e8-8a10-d40894d73a26.JPG)
![img_1597](https://user-images.githubusercontent.com/1307286/39093682-596c547c-461b-11e8-80d2-55929d1943f8.JPG)
![img_1598](https://user-images.githubusercontent.com/1307286/39093683-59872b8a-461b-11e8-87ba-26a2b4e7317f.JPG)

**Comment by waynesi** [comment]
I'm guessing the issue is probably because the memory allocation failure on the takeVideoFocus call. 

For your information, the AA is the only major tweak I installed. I don't have StatusBarTweaks and Speedometer tweaks installed anymore. I never installed the VideoPlayer and CastScreenReceiver. 

I DO have Swapfile tweak installed and the swapfile is stored on a cheap thumb drive.

**Comment by waynesi** [comment]
Another thing is, sometimes I noticed in the log which said Something bad happened ...

![img_1617](https://user-images.githubusercontent.com/1307286/39093752-8c105c88-461c-11e8-9799-db36a0e0efdd.JPG)

Not sure if it has anything to do with the issue.

**Comment by rolanie3** [comment]
I have the same setup minus the swapfile and don't encounter this issue - maybe try removing it?

Sent from my mobile device.

________________________________

**Comment by waynesi** [comment]
I believe it is because of the memory allocation failure. I have the built-in SATNAV (SD card).  I took it out and boom everything started working smoothly. I could switch out and back in, and the music play was no more jerky. I uninstalled and reinstalled the swapfile and put back the SATNAV SD card, and everything seems still working. I will give it a road test tomorrow morning and report back.

@rolanie3 I did my tests before seeing your post, but still much appreciate your advice. I'm wondering, since everything is working now with the swapfile, did the swapfile previously fail because I removed the USB drive from time to time? I understand I'm not supposed to remove it when the system is running, but I was told to only insert the USB drive after the system boots to install the tweaks and I had to remove the USB drive after the installation but before the system reboots. I was hoping the system will still try to mount the swapfile every time after boot even if it failed to do so previously. Maybe I was wrong thinking in that way? Is there a safe procedure to install tweaks after installing the swapfile tweak? Use two USB drives?

**Comment by waynesi** [comment]
@mishan I'm following the FAQ on the https://mazdatweaks.com/faq/ When do I need the to use the SwapFile Tweak? If you use a navigation SD card and/or use the Video Player app or Android Auto often, you want to be using the swapfile. 

In my case, I have the SATNav SD card and I use AA a lot. Ideally I don't ever want to switch out of AA because it _almost_ gives me everything a modem infotainment system should. But I do want to check my trip data, e.g. the coolant temperature and battery level and most importantly my trip MPG, and unfortunately the ODB2AA is no longer working. So I have to switch out to check Speedometer. Also I want to keep my SATNav SD card in the slot, just in case my Android run out of battery after long journey; we all know how weak those USB ports are when charging a phone!

Anyway, I couldn't wait for tomorrow, so just finished a drive around home. With the swapfile reinstalled, I managed to switch between AA, Speedometer and built-in SATNav constantly; 99% of time worked. I did get a "Can't find (or connect, can't remember) the headunit process" error once though and I had to reboot the infotainment system, but couldn't remember what I did to trigger this error. I think my issue was caused by the swapfile which was probably somehow broken, because uninstalling the reinstalling the swapfile was the only thing I did, other than removing the SATNav card and putting it back.

I will try again tomorrow on my longer journey to work and report back. Hopefully we can close this issue after!

**Comment by mishan** [comment]
Yeah the FAQ does say that. I use AA and have the factory SD card I never remove. I don't have issues. Why not try not using swap file unless there are issues? I'd personally only do swap file stuff as a last resort.

On April 23, 2018 9:43:05 AM HST, waynesi <notifications@github.com> wrote:
>@mishan I'm following the FAQ on the https://mazdatweaks.com/faq/ When
>do I need the to use the SwapFile Tweak? If you use a navigation SD
>card and/or use the Video Player app or Android Auto often, you want to
>be using the swapfile. 
>
>In my case, I have the SATNav SD card and I use AA a lot. Ideally I
>don't ever want to switch out of AA because it _almost_ gives me
>everything a modem infotainment system should. But I do want to check
>my trip data, e.g. the coolant temperature and battery level and most
>importantly my trip MPG, and unfortunately the ODB2AA is no longer
>working. So I have to switch out to check Speedometer. Also I want to
>keep my SATNav SD card in the slot, just in case my Android run out of
>battery after long journey; we all know how weak those USB ports are
>when charging a phone!
>
>Anyway, I couldn't wait for tomorrow, so just finished a drive around
>home. With the swapfile reinstalled, I managed to switch between AA,
>Speedometer and built-in SATNav constantly; 99% of time worked. I did
>get a "Can't find (or connect, can't remember) the headunit process"
>error once though and I had to reboot the infotainment system, but
>couldn't remember what I did to trigger this error. I think my issue
>was caused by the swapfile which was probably somehow broken, because
>uninstalling the reinstalling the swapfile was the only thing I did,
>other than removing the SATNav card and putting it back.
>
>I will try again tomorrow on my longer journey to work and report back.
>Hopefully we can close this issue after!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gartnera/headunit/issues/129#issuecomment-383698364

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by waynesi** [comment]
Just finished my commute to work and constantly switching between AA, Speedometer and built-in SATNav was flawless. No reboot needed at all this time. So I reckon this issue can be closed.

The only issue remaining is the audio was very very jerky. I played music on Spotify. When the Spotify was on focus in AA, the audio was smooth. But as soon as I switched to Google Maps on AA, the audio became broken and unbearable, including the voice guide for navigation. I though it might be the interruption from the built-in SATNav, but even after I turned off all the warnings wherever I could, the audio was still broken. Not sure if it is the swapfile on a slow thumb drive.

BTW, I saw on the youtube video that after launching AA, one needs to press Fav + Music to focus the audio channel? I never needed to do so and saw no difference even after doing that. Do we need to do that?

@mishan Thanks I will give it a try.

**Comment by waynesi** [comment]
As @mishan suggested, I uninstalled swapfile and gave it a try. I still could switch between all the apps as afore-described. I have to say I'm very surprised as I expected to see the old issue getting back; but no, still worked. Now I have no idea why I got the initial issue. Maybe the swapfile was in use but the file itself was corrupted?

Anyway, the audio stream was still broken badly. I can only guess maybe it's the process priority? When Spotify is on screen in AA the audio is fine; the audio from the built-in SATNav running at the background is always fine, but it can't explain why the voice guide from Google Maps or Waze is always broken even when those apps are shown in AA. I also noticed, when I stopped playing the music, the music audio still continued for quite a few seconds so long that I often wondered if I did press the pause button. Not sure if it's common to everyone. Anyway, at the end I had to decide to remove the factory SATNav card to fix the audio issue. I would love to know if any other factory SATNav owners have same problem or not.

Earlier I mentioned I also got the "Can't connect to the headunit process" error. I don't know if anyone has the same problem with their Mazda, but every time I start the engine, the screen turns black and then resumes displaying again as if the computer lost power for a couple of seconds. Occasionally I got this "Can't connect" error after this "reboot" if I had AA running before starting the engine. Anyone has the same problem?

**Comment by waynesi** [comment]
Another thought on the jerky audio stream issue...Since all the video and audio data are streamed via the USB connection, then when the audio player is shown on screen, the screen is fairly static and thus the video data consumption is much smaller and thus the audio has bigger bandwidth, so good playback. The factory SATNav's audio never needs to go through the USB bandwidth, so always good playback. But when the Google Maps or Waze is in use, the screen is more dynamic and thus more video bandwidth and not much room for the audio stream for both the music and the voice guide. This theory seems can explain everything very well, and can also explain the question I raised in other issue for better resolution - maybe the built-in USB is just not fast enough? Maybe the WIFI connection is the cure? Still would love to know if anyone else has the same issue with audio though.

**Comment by Trevelopment** [comment]
Have you tried using a better USB cable?  If you are using a crappy cable you will have a crappy connection.

**Comment by waynesi** [comment]
Hi @Trevelopment  Thanks for your advice. Although my cable is not a gold plated one, I won't call it crappy. It's the supplied one in the box. My previous comment on USB bandwidth was a guessing; after all the same cable works fine as long as the factory SATNav card is not inserted. I will try to source a better cable, but it may take time for me to report back.

**Comment by Trevelopment** [comment]
I just suggest that because just using a better cable is a very common solution to this issue and works for most but so is removing the SATNav card because that is definitely what is giving you memory errors. It is probably the reason that the headunit process crashes when you turn off the car too and why your audio starts to get jerky after a while.  Remember that SD has slower I/O speed than USB and much, much slower than internal storage and just think of how much information that navigation software is processing at any given time from all the detailed info that is on the card.

**Comment by waynesi** [comment]
Thanks a lot for your suggestion @Trevelopment . I shall find a good cable and give it a try. Thanks.

**Comment by melvin100** [comment]
@waynesi hello.. did you find any solution bro???

**Comment by waynesi** [comment]
Hi @melvin100  for the initial issue, i.e. failing to relaunch after quit, I reflashed the AA and it worked since then. I'm no longer using the SwapFile BTW. The jerky audio stream issue was still there and I could only resolve the issue by removing the SATNav SD card. Oh, one more thing, as I mentioned in my earlier post, the system always seems lost power for a sec when the engine starts. If AA is started before that, there are good chances the process can't be found and only a reboot can help. So I always manually launch the AA after starting the engine.
