### ISSUE TITLE
Support for Blackberry Android Devices

### ISSUE THREAD

**Issue by Graphictank** [gartnera/headunit#13]
Specifically the Priv.

Successfully installed Android Auto V0.92 into my '15 Mazda3, but when I connect my Blackberry Priv it says it is unsupported. It looks as if the hu_usb.c & hu_uti.h files in /jni need an update but personally I am not sure what the code would be to add.

If someone could help with this I'd GREATLY appreciate it.

**Comment by gartnera** [comment]
I need the vendor id for your phone.

http://www.makeuseof.com/tag/how-to-find-unknown-device-drivers-by-their-vendor-device-id/

**Comment by Graphictank** [comment]
Hi thanks for replying. Walk me through this. How do I get you what you
need?

**Comment by Graphictank** [comment]
I'm looking at the link you sent me.... Hopefully I can get you the info
you need. If not, may need some help. THANK YOU.

**Comment by Graphictank** [comment]
Yo... OK, I'll hook my BlackBerry up and get it to you tomorrow. Many
thanks.

**Comment by Graphictank** [comment]
Hey there,

This looked to be the right one. There wasn't a "Device Instance ID" as the
webpage said, but there was a "path".

USB\VID_0FCA&PID_8031&MI_00\7&1B2D98D9&0&0000


If this is not correct, please let me know & I can look again but after
checking a bunch of the properties, this was the one that looked the most
similar.

Thanks again for your help!!


Best regards,

Steve

**Comment by Graphictank** [comment]
I was trying to update the code myself. I'm guessing that the updates to the code are something like this? Thought I would check here prior to attempting an install.

In hu_uti.h: 

> define USB_VID_0FCA 0x8030  // Blackberry

as well as in hu_usb.c:

> if (vendor == USB_VID_0FCA)
return (5); 

Would that be correct?

**Comment by Graphictank** [comment]
Thanks Alex!

**Comment by Graphictank** [comment]
Last release was awhile ago, still waiting for a new release to verify this is working. Any updates?
