### ISSUE TITLE
Is it possible to increase the max resolution?

### ISSUE THREAD

**Issue by waynesi** [gartnera/headunit#130]
Hi,

I'm using 1.08. I can see the max resolution is set to 800x480. The screen of AA looks quite coarser than other places of the built-in system, so I guess the resolution of my physical screen is better than 800x480 although I can't find any concrete data. I can see other better resolutions are defined in the code, and am wondering if a better option can be chosen. 

I noticed the 720p and 1080p settings are only available in the dev mode of the AA due to a recent bug on Google AA side. I'm not sure if your choice is linked  to this issue. If so, can we expect to see a better resolution once Google fixes on their end?

Thanks.

**Comment by copperx** [comment]
I've been wondering about this for months. Can the resolution of the headunit be changed? And if it is possible, is it a simple configuration change? Or does it need code to be written/rewritten?

**Comment by Trevelopment** [comment]
The screen resolution is only 480p but @lmagder explains what you are seeing perfectly in #84 
> the CMU uses 800x480 but at a 16:9 aspect ratio with non-square pixels. AA doesn't support this. It only supports 800x480 but with square pixels and optionally adding black bars to the sides of the image. So instead we add black bars to make the image 16:9 then crop them off on the car. This results in a non 1-1 pixel mapping but it's close and the correct aspect ratio.
