### ISSUE TITLE
Can I develop my project with this code?

### ISSUE THREAD

**Issue by xuleilx** [gartnera/headunit#131]
I have GAL V0.9 documents, and I found that there are many differences with this project.
Can you tell me what version of the protocol you are developing on?
If possible, give me a copy of the document.Thanks. E-Mail: xuleilx@gmail.com
By the way, Can I develop my project with this code? Does it need certification like Carplay?

**Comment by Serubin** [comment]
This code is published under a GNU derivative license. You can find its terms in the root of the repository. All the information you're asking for should be available within the source code! Happy coding
