### ISSUE TITLE
Opening Device...Nothing found. Waiting

### ISSUE THREAD

**Issue by connerhuff** [gartnera/headunit#132]
Installed Android Auto and it seems it's not connecting.

I guess it's then about screen that comes up that has the names of the developers.  Then below is a box of script.

The last line of the code is: w/home/mazda/headunit/hu/hu_usb-cpp:382: Start : Opening Device 0x1d6b : 0x0002
w/home/mazda/headunit/hu/hu_usb-cpp:382: Start : Opening Device 0x1d6b : 0x0002
w/home/mazda/headunit/hu/hu_usb-cpp:382: Start : Opening Device 0x0424: 0x2640
w/home/mazda/headunit/hu/hu_usb-cpp:382: Start : Nothing found, waiting

**Comment by melvin100** [comment]
Same for me please help. But below i dont have script..

**Comment by Trevelopment** [comment]
Use a better USB cable

**Comment by melvin100** [comment]
ok. i will buy new usb and try again.
