### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by tomcontr** [gartnera/headunit#133]

**Comment by mishan** [comment]
No. 

On June 12, 2018 8:33:29 PM PDT, tomcontr <notifications@github.com> wrote:
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gartnera/headunit/issues/133

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tomcontr** [comment]
Just saying, last modification was 5 months ago...

**Comment by mishan** [comment]
That's not too bad. This project is not dead by any means. Feel free to contribute! There's a lot of discussion in issues. 

On June 12, 2018 8:39:46 PM PDT, tomcontr <notifications@github.com> wrote:
>Just saying, last modification was 5 months ago...
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gartnera/headunit/issues/133#issuecomment-396803671

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mishan** [comment]
@Trevelopment can you close the issue please? I don't have permissions. Thanks
