### ISSUE TITLE
Android 9(pie) issue with wifi connection to android auto

### ISSUE THREAD

**Issue by jpmu** [gartnera/headunit#138]
On updating to Android 9 (pie) the wifi connection to android auto no longer seems to work. Worked fine in Oreo. Works fine if I use the cable.

**Comment by rcin2008** [comment]
Same issue here, I have connected my car with my smartphone and started the server in the application Android Auto but it doesn't start. any solution ? PS: I have Oneplus 6 Android 9 (pie)

**Comment by m3us** [comment]
I have the same issue on a pixel 2xl; will look into it but I think AA searches for the wrong IP like silverchris mentioned.

**Comment by johnnyleitrim** [comment]
I have a potential fix for this that works on Ubuntu, but I'm not sure how to get the compiled code under `mazda` onto my car to test it.  @Trevelopment , how do I get the newly compiled code on?  The directory structure looks different than what's in MZD-AIO.

**Comment by Trevelopment** [comment]
@johnnyleitrim if you make an installer with MZD-AIO you just replace `config/androidauto/data_persist/dev/bin/headunit` with your compiled headunit binary, run installer, ??, profit!

**Comment by johnnyleitrim** [comment]
Thanks @Trevelopment - My change also includes adding a field to `headunit.json` - do I just replace that file in the installer too?

**Comment by Trevelopment** [comment]
yea put that in `config/androidautowifi/`

**Comment by Trevelopment** [comment]
Fixed by #153
