### ISSUE TITLE
Audio stuttering very frequently when navigating with Pixel 3XL 

### ISSUE THREAD

**Issue by iainheng** [gartnera/headunit#143]
I recently switched to Google Pixel 3XL and noticed that my audio stuttering so bad when navigating with Google Map or Waze. Audio stuttering almost every turns on the map. 

The audio stuttering was much less frequent on my previous phone OG Pixel. Does any Pixel 3 owner experience the same?

Any optimizations we can make on the phone or headunit? I have tried disabled the adaptive battery optimizations on Android Pie without success. I have AA version 1.10+ installed from AIO.

**Comment by retaker** [comment]
Same with Oneplus 5, trying newer version now...

**Comment by blackdetail** [comment]
If you have Mazda Nav Card in the SD slot, remove the SD card and see if it is better.

**Comment by zahitkara** [comment]
I think that's because AIO AA runs at 60fps while the official AA and other cars i drove with AA runs at 30fps. Even though Trez says it's programmed to run at 30fps mine definitely works at 60fps. AA can't handle 60fps i think and the audio shutters because of that. That's my opinion.

**Comment by zahitkara** [comment]
> How do you know its running at 60fps? Also, how do we set it to run at 30fps?

I don't there is a setting to set it but i can record a video with a phone capable of recording 60 fps to show it to you.

**Comment by Trevelopment** [comment]
I don't know if this helps but I found part of this code in the new MZD v70 FW and I tried using it in headunit-wrapper
```sh
echo 41943040 > /proc/sys/net/core/rmem_max
echo 41943040 > /proc/sys/net/core/wmem_max
echo 17825792 > /proc/sys/net/core/rmem_default
echo 17825792 > /proc/sys/net/core/wmem_default
echo 4096 17825792 41943040 > /proc/sys/net/ipv4/tcp_rmem
echo 4096 17825792 41943040 > /proc/sys/net/ipv4/tcp_wmem
```
I am not a Linux expert but I think this might help a bit.  I got the actual numbers from /usr/bin/autostart in v70 but only the "rmem" values were in it I added the "wmem".  Also, I tried this too but in testing it seemed to make things worse `echo 4096 17825792 41943040 > /proc/sys/net/ipv4/tcp_mem`

**Comment by gh123man** [comment]
I suspect this could help with AA over WiFi - but the USB mode does not use TCP or the linux network stack to transfer data. 
Full disclosure - I have never even tried AA over WiFi so I am unsure what the audio situation is there. 

Do you know where I can obtain a dump of v70?

Also I understand that the official AA/CarPlay retrofit requires a new USB board. Perhaps they are using a higher bandwidth USB port to get around these issues?
