### ISSUE TITLE
Android Auto audio lag during animations *repost*

### ISSUE THREAD

**Issue by Krogsager** [gartnera/headunit#149]
Quick disclaimer: I also posted this issue [here ](https://github.com/Trevelopment/MZD-AIO/issues/49) but became unsure as where it belongs to.

Issue:
When driving with Google Maps on the car screen and listening to Google Play Music:
I experience audio lag when the google maps view changes perspective. E.g. when the maps zooms in close to a turn, or rotates at a roundabout, music that is playing choppy.

Setup:
MZD-AIO-TI v2.8.4 - installed Android Auto on my European Mazda3, on FW 56.00
Using android auto 4.1.590944-release
Android 9 phone with USB connected.

Other: I had to do the 180 degrees GPS fix.

**Comment by wikitiki33** [comment]
I can second this issue. Latest MZD-AIO installed on North American 2015 Mazda3 on FW 55.00.760.

Lag is almost never noticeable until I have maps open, then the whole thing stutters and gets a pretty harsh lag.

**Comment by Krogsager** [comment]
Discussion is under way in the original post.
https://github.com/Trevelopment/MZD-AIO/issues/49
