### ISSUE TITLE
Google maps gps signal randomly reverses/teleports

### ISSUE THREAD

**Issue by Krogsager** [gartnera/headunit#150]
So I've experienced that gmaps on AA randomly thinks I'm driving backwards and jumping back and forth on the road/teleporting to different lanes...
I've installed AA with AIO tweaks and set the system is set to use the car's gps and the reverse 180° fix.

When using the built-in navigation I get stable behavior.
When using gmaps on my phone I get stable behavior.

Is anyone else experiencing this?

**Comment by Trevelopment** [comment]
So did you check both of the options on the second line?  If you did try only checking the reverse car GPS.  If you didn't then try checking both of them. If you tried both of those try not checking either option.

**Comment by Krogsager** [comment]
I forgot to say that AA gmaps works fine ~90% of the time. The problem is happening occationally.
Should I still try to reinstall?

**Comment by Trevelopment** [comment]
There will be times when it is not 100% reliable but a reset of the system will kick it back into working again.  You can try reinstalling with changed options to see if it fixes your other issue.

**Comment by Krogsager** [comment]
I've reinstalled AA with both options checked (rotate 180 degrees + disable car GPS). Within a few days.

**Comment by Krogsager** [comment]
> I've reinstalled AA with both options checked (rotate 180 degrees + disable car GPS). Will test within a few days.

Google Maps with Android Auto is now stable.
