### ISSUE TITLE
unplugging phone and exiting AA

### ISSUE THREAD

**Issue by paddyyyyyy** [gartnera/headunit#151]
Hi,
Whenever I unplug my phone or manually quit AA, the screen turns blank and stays like that until I press Nav/media buttons. Is this normal?

**Comment by Trevelopment** [comment]
It is normal on FW v59.00.540+  What FW are you running?

**Comment by paddyyyyyy** [comment]
Ok. I'm on 59.00.545

**Comment by Trevelopment** [comment]
Then yes that happens on your FW version
