### ISSUE TITLE
Maybe is my fault, can you help-me?

### ISSUE THREAD

**Issue by Hendrix1** [gartnera/headunit#161]
Hi,
Firstly thanks for your help and your project.

I live in europe, my mazda 6 firmware version 56.00.513.
I installed the AA version 1.11 via MZD-AIO b2.8.4-1.

Maybe is a dumb question, but, when i connect my phone to the usb in the car, nothing happen.
and then, I go to application and click in android auto and receive a message:

Connect with usb: connect android phone to vehicle cable to start ( and Im connected).
Connect via Wifi: make a hotsopt in yout phone to start (something like this). (I tried this one as well, still the same)

No errors appear, that is the why I think is a stupid question, but I reinstalled 3x and still the same.

Maybe can you help-me, and sorry for the question.
Thanks!

**Comment by Trevelopment** [comment]
Try a different USB cable

**Comment by Hendrix1** [comment]
Ok, thank you, Ill let you know.

Regards,

**Comment by Hendrix1** [comment]
But would it work in the wifi isn't it?

**Comment by Trevelopment** [comment]
Did you enable developer mode in AA on your phone and start the headunit server?

**Comment by Hendrix1** [comment]
Yes, I did it in my normal android, i did not do in the android auto.

**Comment by Trevelopment** [comment]
https://mazdatweaks.com/androidauto/
PHONE: Enable Developer Settings in Android Auto, Create a personal hotspot
CAR : Connect Wifi to personal hotspot
PHONE: Open Android Auto app and go to “about”. Open the menu and tap “Start Head unit Server”
CAR: Android Auto Headunit will start automatically
Or get a better USB cable that will work too.

**Comment by Trevelopment** [comment]
Oh I forgot that version Wifi doesn't work with Android Pie.  I have tested the Wifi fixes in the next version but its not released yet.

**Comment by Hendrix1** [comment]
Right, I have another phone, android 8.1 I'll try with this one so, via wifi. I let you know

**Comment by Hendrix1** [comment]
Good morning, today I tried with another phone, android 8.1 via cable and worked great! 
Thank you very much for your information.

Just to inform So the android 9 still not working.

**Comment by duckunix** [comment]
Just a random data point, I have been using AA on my Pixel 2 since 8.something, and I am currently on 10, and it is working well.

**Comment by monin01** [comment]
> Oh I forgot that version Wifi doesn't work with Android Pie. I have tested the Wifi fixes in the next version but its not released yet.

Hello. Do you know when the new version with the Android Pie fix will be released?
