### ISSUE TITLE
Reverse display with the new AA style

### ISSUE THREAD

**Issue by csirek** [gartnera/headunit#163]
Hi 
I am using the latest official (2.8.4) AIO package and the AA from it. The latest AA app ugrade from Google enabled the new beta setup for the display and menu structure. In this case we got a application menu  like in Android and deticated microphone button and so on.

So i enabled this feature and the new menus and buttons appear reversed than the normal as i see it in different videos or my boss's car where are official AA in the car (Ford Focus). The bottom of the display where are the microphone, the notification bell are the left side, and the menu button with the apps are the right side (the most far point from the car driver). These are reversed as the normal. I am not sure these are an AA app bug or the Devs can do anything with it. 
If necessary i can make a photo about it.

**Comment by mishaaq** [comment]
It may be related to the car's left/right hand drive option. I have the same buttons' placement as you described having left-hand drive car.

**Comment by csirek** [comment]
I have a left-hand drive car but i didn't any setup where i can set up the driver side :(

**Comment by EQMOD** [comment]
currently it is hardcoded on the hu_aap.cpp code;

    Set TRUE for Right Hand Drive, Set FALSE for Left Hand drive

    carInfo.set_head_unit_name("Mazda Connect");
    carInfo.set_car_model("Mazda");
    carInfo.set_car_year("2016");
    carInfo.set_car_serial("0001");
    carInfo.set_driver_pos(true);     // <<<<<<---- DRIVER POSITION
    carInfo.set_headunit_make("Mazda");
    carInfo.set_headunit_model("Connect");
    carInfo.set_sw_build("SWB1");
    carInfo.set_sw_version("SWV1");
    carInfo.set_can_play_native_media_during_vr(false);
    carInfo.set_hide_clock(false);
