### ISSUE TITLE
Should I update the readme.md

### ISSUE THREAD

**Issue by m3us** [gartnera/headunit#164]
I noticed the instructions on https://mazdatweaks.com/androidauto/ where slightly outdated and 
 wrote this to help others
https://github.com/gartnera/headunit/wiki#instructions-to-compile-current-code-using-ubuntu-1604

Should I update the readme with it

**Comment by Trevelopment** [comment]
Go for it you can update mazdatweaks.com too if you want to: https://github.com/Trevelopment/mazdatweaks/blob/master/aa.md
or I will get to it eventually
