### ISSUE TITLE
AA Focus Lost on (Certain) Calls

### ISSUE THREAD

**Issue by SSyl** [gartnera/headunit#165]
I'm on AA 1.11, AIO 2.8.4, Mazda Firmware 55.00.753. 2015 Mazda 3 sGT.

Almost all of the time that you call using a third party app such as Telegram (i.e. not using the phone's dialer), you get kicked out of Android Auto and taken to Mazda's phone call screen. This wouldn't be a huge issue if you could back out, but you're stuck on the screen and can't get out by pressing any button (e.g. home, back, nav, end call, etc.) and the touch screen is non-responsive (although things like the call time still ticks away). The only way to fix it is by disconnecting your phone from the USB and connecting it again, which forces AA to pop back up (but also disconnects the call). Otherwise, if that doesn't work, you have to reset via the back+nav+volume button which is never ideal while driving.

On previous versions of Android Auto (I think I was using 1.09 before updating to 1.11), the home button would force whatever screen you were on to go back to Mazda's Infotainment home screen. This allowed you to at least go back through the app screen and open up AA again or get the screen responsive again. Since the home button was remapped to go to the AA home screen rather than the Mazda home screen, it doesn't let you force yourself out of situations like this.

If there's not an easy fix for this, could we implement a way to make the home button or some other Mazda button to force you back to the Mazda screen?

I'm going to downgrade my AA version in the meantime since I use Telegram as my main calling app for my friends and family.

**Comment by Trevelopment** [comment]
Try this version http://aa.mazdatweaks.win if you get kicked out of AA you can hold the home button for 3 seconds to get back in.

**Comment by SSyl** [comment]
Yep, AA 1.12 fixes it by being able to hold the home button.
