### ISSUE TITLE
Audio only heard when music playing on V1.11+

### ISSUE THREAD

**Issue by achuman** [gartnera/headunit#166]
Ever since V1.11, I don't get audio from maps or notifications unless I play music through spotify.  Once spotify takes control of the audio channel the notifications work.

Currently on V1.12

**Comment by Trevelopment** [comment]
And on 1.12 the voice guided navigation doesn't work?    Try it again, I tested it a lot the navigation should take transient audio focus then it will release focus back to the Mazda audio or whatever audio was playing before.  I just tried it myself, it works.

**Comment by achuman** [comment]
It definitely doesn't work for me.

**Comment by achuman** [comment]
Is there any way to enable logging or something so that I can see what it's doing?

**Comment by Trevelopment** [comment]
yes so reinstall v1.12 and in `config/androidautowifi/headunit-wrapper` change the third line from `DEBUG=0` to `DEBUG=1`
The log file will be written to `/data/headunit.log` you can retrieve it manually or whenever you install AA with that installer it will copy that log file onto the root of your USB drive.  Post the log up here and reopen the issue when you get it.

**Comment by Trevelopment** [comment]
Or if you have SSH skills `sed -i s/DEBUG=0/DEBUG=1/ /data_persist/dev/bin/headunit-wrapper`

**Comment by achuman** [comment]
I managed to pull the log: 

START HEADUNIT LOG - 10/14/19 01:35:00
uname:
 sysname: Linux
 release: 3.0.35
 version: #1 SMP PREEMPT Fri Nov 20 16:39:36 IST 2015
 machine: armv7l
libprotoversion: 2.6.1
libusb_get_version:
 version: 1.0.9.0
 rc: 
 describe: 
openssl version: OpenSSL 1.0.2h  3 May 2016 (0x1000208f)
=== headunit-usb ===
{
    "launchOnDevice": true,
    "carGPS": true,
    "wifiTransport": false,
    "phoneIpAddress": "192.168.43.1",
    "reverseGPS": false
}
====================

(gst-plugin-scanner:4397): GStreamer-CRITICAL **: gst_pad_template_new: assertion `caps != NULL' failed

(gst-plugin-scanner:4397): GStreamer-CRITICAL **: gst_element_class_add_pad_template: assertion `GST_IS_PAD_TEMPLATE (templ)' failed
[1;34mMAX resolution 800x480
[0m
(gst-plugin-scanner:4657): GStreamer-CRITICAL **: gst_pad_template_new: assertion `caps != NULL' failed

(gst-plugin-scanner:4657): GStreamer-CRITICAL **: gst_element_class_add_pad_template: assertion `GST_IS_PAD_TEMPLATE (templ)' failed
headunit version: v1.12-5-ge9b477b 
json config parsed
Looping
DBus::Glib::BusDispatcher attached
Making debug connections
snd_asoundlib_version: 1.0.24.1
dumpState({"pretty":false,"svc":"SRCS"})
{"HMI":{},"APP":["26.InfoUser.SMS..NotPlaying","25.HighAlert.BTECAALERT..NotPlaying","24.MP911.BTECA..NotPlaying","23.InfoUser.PHONEBOOK..NotPlaying","22.VR.SYSVR..NotPlaying","21.Media.AHA..NotPlaying","20.Media.Pandora..NotPlaying","19.Media.Stitcher..NotPlaying","18.Media.TV..NotPlaying","9.Media.LM..NotPlaying","1.Media.AUX..NotPlaying","15.Telephony.BTHF..NotPlaying","3.Media.DAB..NotPlaying","2.Media.CD..NotPlaying","5.Media.AM..NotPlaying","4.Media.XM..NotPlaying","7.LowAlert.TA..NotPlaying","6.Media.FM.gained.playing","14.Media.BTMUSIC..NotPlaying","8.Media.HAR..NotPlaying","16.MedAlert.BTHFALERT..NotPlaying","17.Media.DVD..NotPlaying","13.Media.USB..NotPlaying","12.InfoUser.RINGTONEVOL..NotPlaying","11.InfoMix.NAVIVOL..NotPlaying","10.InfoUser.BTHFVOL..NotPlaying"]}
Found stream SMS session id 26
Found stream BTECAALERT session id 25
Found stream BTECA session id 24
Found stream PHONEBOOK session id 23
Found stream SYSVR session id 22
Found stream AHA session id 21
Found stream Pandora session id 20
Found stream Stitcher session id 19
Found stream TV session id 18
Found stream LM session id 9
Found stream AUX session id 1
Found stream BTHF session id 15
Found stream DAB session id 3
Found stream CD session id 2
Found stream AM session id 5
Found stream XM session id 4
Found stream TA session id 7
Found stream FM session id 6
Found stream BTMUSIC session id 14
Found stream HAR session id 8
Found stream BTHFALERT session id 16
Found stream DVD session id 17
Found stream USB session id 13
Found stream RINGTONEVOL session id 12
Found stream NAVIVOL session id 11
Found stream BTHFVOL session id 10
openSession({"busName":"com.jci.usbm_am_client","destination":"Cabin","objectPath":"/com/jci/usbm_am_client"})
{"sessionId":27}
registerAudioStream({"focusType":"permanent","sessionId":27,"streamName":"MLENT","streamType":"Media"})
{}
openSession({"busName":"com.jci.usbm_am_client","destination":"Cabin","objectPath":"/com/jci/usbm_am_client"})
{"sessionId":28}
registerAudioStream({"focusType":"transient","sessionId":28,"streamName":"MLENT","streamType":"InfoUser"})
{}
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x1d6b : 0x0002
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x1d6b : 0x0002
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x0424 : 0x2640
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x18d1 : 0x4ee1
W: /home/mazda/headunit/hu/hu_usb.cpp:399: Start : Device 0x18d1 : 0x4ee1 responded with protocol ver 2
W: /home/mazda/headunit/hu/hu_usb.cpp:457: Start : Wating for the device to reconnect
W: /home/mazda/headunit/hu/hu_uti.cpp:375: wait_for_device_connection : udev device removeed | node:/dev/bus/usb/002/004, subsystem:usb, devtype:usb_device

W: /home/mazda/headunit/hu/hu_uti.cpp:375: wait_for_device_connection : udev device added | node:/dev/bus/usb/002/005, subsystem:usb, devtype:usb_device

W: /home/mazda/headunit/hu/hu_usb.cpp:478: Start : Found OAP Device
E: /home/mazda/headunit/hu/hu_usb.cpp:482: Start : Error libusb_claim_interface usb_err: -5 (Entity not found)
E: /home/mazda/headunit/hu/hu_usb.cpp:196: Stop : Done libusb_release_interface usb_err: -5 (Entity not found)
E: main.cpp:236: main : Something bad happened
closeSession({"sessionId":27})
{}
closeSession({"sessionId":28})
{}
DBus::Glib::BusDispatcher attached
Making debug connections
snd_asoundlib_version: 1.0.24.1
dumpState({"pretty":false,"svc":"SRCS"})
{"HMI":{},"APP":["22.VR.SYSVR..NotPlaying","26.InfoUser.SMS..NotPlaying","25.HighAlert.BTECAALERT..NotPlaying","24.MP911.BTECA..NotPlaying","23.InfoUser.PHONEBOOK..NotPlaying","21.Media.AHA..NotPlaying","20.Media.Pandora..NotPlaying","19.Media.Stitcher..NotPlaying","18.Media.TV..NotPlaying","9.Media.LM..NotPlaying","1.Media.AUX..NotPlaying","15.Telephony.BTHF..NotPlaying","3.Media.DAB..NotPlaying","2.Media.CD..NotPlaying","5.Media.AM..NotPlaying","4.Media.XM..NotPlaying","7.LowAlert.TA..NotPlaying","6.Media.FM.gained.playing","14.Media.BTMUSIC..NotPlaying","8.Media.HAR..NotPlaying","16.MedAlert.BTHFALERT..NotPlaying","17.Media.DVD..NotPlaying","13.Media.USB..NotPlaying","12.InfoUser.RINGTONEVOL..NotPlaying","11.InfoMix.NAVIVOL..NotPlaying","10.InfoUser.BTHFVOL..NotPlaying"]}
Found stream SYSVR session id 22
Found stream SMS session id 26
Found stream BTECAALERT session id 25
Found stream BTECA session id 24
Found stream PHONEBOOK session id 23
Found stream AHA session id 21
Found stream Pandora session id 20
Found stream Stitcher session id 19
Found stream TV session id 18
Found stream LM session id 9
Found stream AUX session id 1
Found stream BTHF session id 15
Found stream DAB session id 3
Found stream CD session id 2
Found stream AM session id 5
Found stream XM session id 4
Found stream TA session id 7
Found stream FM session id 6
Found stream BTMUSIC session id 14
Found stream HAR session id 8
Found stream BTHFALERT session id 16
Found stream DVD session id 17
Found stream USB session id 13
Found stream RINGTONEVOL session id 12
Found stream NAVIVOL session id 11
Found stream BTHFVOL session id 10
openSession({"busName":"com.jci.usbm_am_client","destination":"Cabin","objectPath":"/com/jci/usbm_am_client"})
{"sessionId":29}
registerAudioStream({"focusType":"permanent","sessionId":29,"streamName":"MLENT","streamType":"Media"})
{}
openSession({"busName":"com.jci.usbm_am_client","destination":"Cabin","objectPath":"/com/jci/usbm_am_client"})
{"sessionId":30}
registerAudioStream({"focusType":"transient","sessionId":30,"streamName":"MLENT","streamType":"InfoUser"})
{}
W: /home/mazda/headunit/hu/hu_usb.cpp:478: Start : Found OAP Device
W: /home/mazda/headunit/hu/hu_usb.cpp:486: Start : OK libusb_claim_interface usb_err: 0 (Success)
W: /home/mazda/headunit/hu/hu_usb.cpp:500: Start : Done get_config_descriptor config: 0x67b008  num_int: 1
W: /home/mazda/headunit/hu/hu_usb.cpp:525: Start : iusb_ep_in: 0x81
W: /home/mazda/headunit/hu/hu_usb.cpp:532: Start : iusb_ep_out: 0x01
W: /home/mazda/headunit/hu/hu_ssl.cpp:209: hu_ssl_begin_handshake : SSL_do_handshake() ret: -1
W: /home/mazda/headunit/hu/hu_ssl.cpp:65: send_ssl_handshake_packet : BIO_read() HS client req ret: 307
W: /home/mazda/headunit/hu/hu_ssl.cpp:232: hu_handle_SSLHandshake : BIO_write() server rsp ret: 2311
W: /home/mazda/headunit/hu/hu_ssl.cpp:235: hu_handle_SSLHandshake : SSL_do_handshake() ret: -1
W: /home/mazda/headunit/hu/hu_ssl.cpp:65: send_ssl_handshake_packet : BIO_read() HS client req ret: 1224
W: /home/mazda/headunit/hu/hu_ssl.cpp:232: hu_handle_SSLHandshake : BIO_write() server rsp ret: 51
W: /home/mazda/headunit/hu/hu_ssl.cpp:235: hu_handle_SSLHandshake : SSL_do_handshake() ret: 1
W: /home/mazda/headunit/hu/hu_ssl.cpp:261: hu_handle_SSLHandshake :   SET: iaap_state: 2 (hu_STATE_STARTED)
W: /home/mazda/headunit/hu/hu_aap.cpp:1358: hu_aap_start : Starting HU thread
Starting Android Auto...
Bluetooth MAC: 0C:D9:C1:83:03:50
W: /home/mazda/headunit/hu/hu_aap.cpp:567: hu_handle_ServiceDiscoveryRequest : Found BT address 0C:D9:C1:83:03:50. Exposing Bluetooth service
Nightmode service connection established.
GPS service connection established.
json config parsed
W: gps/mzd_gps.cpp:56: ReadStatus : Read status changed commandReply 2 status 1

W: /home/mazda/headunit/hu/hu_aap.cpp:660: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 4
audioMgrReleaseAudioFocus()
AudioFocusHappend(0)
BluetoothPairingRequest: phone_address: "7C:D9:5C:BB:33:2E"
pairing_method: BLUETOOTH_PARING_METHOD_HFP

[1;32mMFW_GST_ISINK_PLUGIN 3.0.5 build on Nov 19 2015 21:35:06.
[0m[1;32mvpudec versions :)
[0m[1;32m	plugin: 3.0.5
[0m[1;32m	wrapper: 1.0.28(VPUWRAPPER_ARM_LINUX Build on Nov 19 2015 21:30:18)
[0m[1;32m	vpulib: 5.4.10
[0m[1;32m	firmware: 2.1.8.34588
[0mhwbuf allocator zone(577536) created
[1;34mVS0 created. in fmt[NV12] win(0,0-800,480:800x480) out win(0,-20-800,500:800x520)
[0m[1;34mset deinterlace mode 0
[0mE: hud/hud.cpp:96: hud_thread_func : DBUS: hud_send failed org.freedesktop.DBus.Error.UnknownMethod: Method "SetHUD_Display_Msg2" with signature "(sy)" on interface "com.jci.vbs.navi.tmc" doesn't exist


W: /home/mazda/headunit/hu/hu_aap.cpp:660: hu_handle_AudioFocusRequest : AudioFocusRequest Focus Request AA_CH_CTR: 3
W: callbacks.cpp:681: HandleNaviTurn : NAVTurnMessage: turn_side: 3, turn_event: 1, turn_number: -1, turn_angle: -1, event_name: Metroplex Ave
BluetoothPairingRequest: phone_address: "7C:D9:5C:BB:33:2E"
pairing_method: BLUETOOTH_PARING_METHOD_HFP

BluetoothPairingRequest: phone_address: "7C:D9:5C:BB:33:2E"
pairing_method: BLUETOOTH_PARING_METHOD_HFP

BluetoothPairingRequest: phone_address: "7C:D9:5C:BB:33:2E"
pairing_method: BLUETOOTH_PARING_METHOD_HFP

BluetoothPairingRequest: phone_address: "7C:D9:5C:BB:33:2E"
pairing_method: BLUETOOTH_PARING_METHOD_HFP

KEY_N
KEY_N
KEY_N
KEY_N
KEY_M
KEY_M
KEY_M
KEY_M
KEY_N
KEY_N
E: /home/mazda/headunit/hu/hu_usb.cpp:291: libusb_callback : libusb_callback: abort
W: /home/mazda/headunit/hu/hu_usb.cpp:231: usb_recv_thread_main : Requested to exit
W: /home/mazda/headunit/hu/hu_usb.cpp:240: usb_recv_thread_main : libusb_handle_events_completed: 2 (hu_STATE_STARTED)
W: /home/mazda/headunit/hu/hu_usb.cpp:242: usb_recv_thread_main : USB thread exit
DisconnectionOrError
quitting...
waiting for nm_thread
waiting for gps_thread
waiting for hud_thread
shutting down
closeSession({"sessionId":29})
{}
closeSession({"sessionId":30})
{}
[1;34mVS0 destroyed, force=0!
[0mhwbuf allocator zone(577536) destroied.
waiting for input_thread
[1;32m[--->FINALIZE isink
[0mDBus::Glib::BusDispatcher attached
Making debug connections
snd_asoundlib_version: 1.0.24.1
dumpState({"pretty":false,"svc":"SRCS"})
{"HMI":{},"APP":["21.Media.AHA..NotPlaying","22.VR.SYSVR..NotPlaying","26.InfoUser.SMS..NotPlaying","25.HighAlert.BTECAALERT..NotPlaying","24.MP911.BTECA..NotPlaying","23.InfoUser.PHONEBOOK..NotPlaying","20.Media.Pandora..NotPlaying","19.Media.Stitcher..NotPlaying","18.Media.TV..NotPlaying","9.Media.LM..NotPlaying","1.Media.AUX..NotPlaying","15.Telephony.BTHF..NotPlaying","3.Media.DAB..NotPlaying","2.Media.CD..NotPlaying","5.Media.AM..NotPlaying","4.Media.XM..NotPlaying","7.LowAlert.TA..NotPlaying","6.Media.FM.gained.playing","14.Media.BTMUSIC..NotPlaying","8.Media.HAR..NotPlaying","16.MedAlert.BTHFALERT..NotPlaying","17.Media.DVD..NotPlaying","13.Media.USB..NotPlaying","12.InfoUser.RINGTONEVOL..NotPlaying","11.InfoMix.NAVIVOL..NotPlaying","10.InfoUser.BTHFVOL..NotPlaying"]}
Found stream AHA session id 21
Found stream SYSVR session id 22
Found stream SMS session id 26
Found stream BTECAALERT session id 25
Found stream BTECA session id 24
Found stream PHONEBOOK session id 23
Found stream Pandora session id 20
Found stream Stitcher session id 19
Found stream TV session id 18
Found stream LM session id 9
Found stream AUX session id 1
Found stream BTHF session id 15
Found stream DAB session id 3
Found stream CD session id 2
Found stream AM session id 5
Found stream XM session id 4
Found stream TA session id 7
Found stream FM session id 6
Found stream BTMUSIC session id 14
Found stream HAR session id 8
Found stream BTHFALERT session id 16
Found stream DVD session id 17
Found stream USB session id 13
Found stream RINGTONEVOL session id 12
Found stream NAVIVOL session id 11
Found stream BTHFVOL session id 10
openSession({"busName":"com.jci.usbm_am_client","destination":"Cabin","objectPath":"/com/jci/usbm_am_client"})
{"sessionId":31}
registerAudioStream({"focusType":"permanent","sessionId":31,"streamName":"MLENT","streamType":"Media"})
{}
openSession({"busName":"com.jci.usbm_am_client","destination":"Cabin","objectPath":"/com/jci/usbm_am_client"})
{"sessionId":32}
registerAudioStream({"focusType":"transient","sessionId":32,"streamName":"MLENT","streamType":"InfoUser"})
{}
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x1d6b : 0x0002
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x1d6b : 0x0002
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x0424 : 0x2640
W: /home/mazda/headunit/hu/hu_usb.cpp:466: Start : Nothing found, waiting
W: /home/mazda/headunit/hu/hu_uti.cpp:375: wait_for_device_connection : udev device added | node:/dev/bus/usb/002/006, subsystem:usb, devtype:usb_device

W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x1d6b : 0x0002
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x1d6b : 0x0002
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x0424 : 0x2640
W: /home/mazda/headunit/hu/hu_usb.cpp:382: Start : Opening device 0x058f : 0x6387
W: /home/mazda/headunit/hu/hu_usb.cpp:466: Start : Nothing found, waiting

**Comment by achuman** [comment]
This might be whats causing the issue: [0mE: hud/hud.cpp:96: hud_thread_func : DBUS: hud_send failed org.freedesktop.DBus.Error.UnknownMethod: Method "SetHUD_Display_Msg2" with signature "(sy)" on interface "com.jci.vbs.navi.tmc" doesn't exist

**Comment by Trevelopment** [comment]
What FW version  are you using?  I looked at the file history of  [mazda/dbus/cmu_interfaces.xml](https://github.com/gartnera/headunit/blame/master/mazda/dbus/cmu_interfaces.xml#L5226) and in the older scrape of the cmu that method doesn't exist so maybe there needs to be something to check that methods existence before calling it.  what is the c++ equivalent of `(typeof SetHUD_Display_Msg2 === 'function')`?
Also Is that the place in the log where the navigation is suppose to give you some voice guidance?

**Comment by achuman** [comment]
I was on the V55 ADR version.  Did an update to V59 last night to see if it makes any difference.  The HUD is fixed now, I'm getting the visual navigation prompts on the HUD.

The Navigation audio still doesn't work though.  Where exactly can I find the log when I ssh in?  I looked in the install script and it copies it from /tmp/mnt/data/headunit.log but I couldn't find a headunit log file there.

**Comment by Trevelopment** [comment]
Cool, did you remember to change `DEBUG=1`?

**Comment by achuman** [comment]
yeah I did, but I might not have restarted before I drove off (can't remember now).  Just to clarify, is the full path  /tmp/mnt/data/headunit.log as I've noticed that logging in with ssh vs a file manager starts in a different path.

**Comment by Trevelopment** [comment]
you can get there with /data/headunit.log

**Comment by achuman** [comment]
I'll email you the latest log, it has plenty of HUD calls in it with identifying information in it.

**Comment by matkeith** [comment]
Jesus how do I unsubscribe from this? I deleted my GitHub account already

**Comment by Trevelopment** [comment]
Did you try clicking "unsubscribe" at the bottom of the email?  🥇
