### ISSUE TITLE
Need coding help on Videofocus detection at main.cpp

### ISSUE THREAD

**Issue by EQMOD** [gartnera/headunit#167]
Hello, i did some customization on the Android auto code which causes it to crash whenever the backup camera is activated.  The code is located at main.cpp which calls pipeline object modification on gstreamer. My question, the callback for videofocus is located at callbacks.cpp and I need to check if videofocus is true before i call the gstreamer function at main.cpp. Can someone give me an example how to get videofocus state  at main.cpp side ? Thanks.

at main.cpp pseudo code;

if AA-videofocus is true
      call mygstreamerfunc();

mygstreamer function crashes if the backup camera is active.

Thank you again.

**Comment by Trevelopment** [comment]
What are you trying to accomplish with this?  If you are trying to get videoFocus in the main function loop I believe you can just call it with callbacks.videoFocus
