### ISSUE TITLE
AA won't start.

### ISSUE THREAD

**Issue by shchan142** [gartnera/headunit#17]
Started once and haven't since...

**Comment by shchan142** [comment]
The USB notification on my phone jus constantly goes on and off when this happens. Does anyone know what I am doing wrong. I dlwd the latest file 93...

**Comment by mbt28** [comment]
I think, there is a powering issue. You should use external powered cable.

**Comment by ignabel** [comment]
This happened to me when I had a USB drive with music in the other USB port in the car. Remove it, reboot both CMU and phone (just in case) and retry.
