### ISSUE TITLE
Debugging Connection Refusal to Mazda AIO

### ISSUE THREAD

**Issue by Anomalyzero** [gartnera/headunit#170]
In the past few months, I've begun to encounter a frustratingly inconsistent issue getting Android Auto to connect via USB to my 2015 Mazda 3 head unit.

Basically, Android Auto will not start on the Mazda Infotainment screen. There are no error messages as far as I can tell. I do have Bluetooth Launch enabled, so when the car starts and connects to my phone, the app automatically starts on my phone. The application starts and runs on the phone fine, the headunit process does not start, even if I navigate to it in the Applications menu.

#### Everything about the problem is inconsistent. 
- The issue happens seemingly at random. Sometimes not happening for days, then happening repeatedly in a single day. There is no pattern as I can discern, not without more information or logging.

Ways to resolve the problem are similarly all over the place:
- Sometimes pulling the USB cable once and re-plugging it will cause Android Auto to launch
- Sometimes pulling the USB cable repeatedly over and over again will eventually cause Android Auto to launch
- Sometimes closing the Android Auto app on the phone and reopening it manually will cause Android Auto to launch on the CMU
- Sometimes the above does not work, rebooting the Mazda CMU (NAV+MUTE+BACK) will cause Android Auto on the reboot
- Sometimes rebooting the phone will cause Android Auto to start after the reboot.
- Sometimes rebooting both the phone and the headunit *does not* work

Usually, something of the above will work, but a couple times over the past few months, seemingly none of them have worked after working through all of the known solutions. It's also worth noting that there was a clear point that this all started, maybe in October or so. I seem to remember a big update to the UI at about the same time. Could be related.

#### This really leaves me with 2 questions:
1. Is this issue already known to anyone? I tried searching but didn't seem to find anything that fits. If it is, can anyone direct me to threads/issues on the subject?
2. How can I access any relevant logs to begin probing the problem? I'm a developer and have some experience with software development, but I haven't worked in this environment before and don't really know where to start to begin debugging the issue. Any development guides would also be welcome.

**Comment by Trevelopment** [comment]
1. Yes, not only is this known but it constantly changes with every update of AA on your phone.  Also, it can be because on many, many other factors pertaining to the state of your phone at the time.
2. In AIO when you choose AA in the top right corner of the AA options is "Debug Logging" you will see it onmouseover.  Also, there is a newer version of AA headunit app for you to try [Here](http://aa.mazdatweaks.win) if you don't have it already.  So you unzip that and open the file `config/androidauto/data_persist/dev/bin/headunit-wrapper` change `DEBUG=0` to `DEBUG=1` then you get a log @ `/data/headunit.log`
