### ISSUE TITLE
HUD directions

### ISSUE THREAD

**Issue by rquanleon** [gartnera/headunit#171]
Hi, I'm testing 1.12 AA with waze.

The HUD randomly shows turns directions and gets stuck with it.

I tried  Settings -> HUD -> disable navigation but randomly shows turns.

My version:
56.00.240 4A N
DB 00.05.000
failsafe 56.00.240

Can I disable HUD notifications?

thanks,

**Comment by achuman** [comment]
I had the same issue, update your Mazda software to 59.

**Comment by rquanleon** [comment]
> I had the same issue, update your Mazda software to 59.

Thank you for your answer, I update to 59.00.502 + id7 this week, everything seems to work well except of this:

AA 1.12 crashes when using waze on AA and listening music on youtube with cellphone.

this didn't happen with 56.00.240

**Comment by achuman** [comment]
That's a problem with Android auto itself. There is a big in the latest google play services that causes that. Mine has updated and is now fine again. Just check for play store updates.

**Comment by coddicat** [comment]
Hi everyone! I have the same issue with hud. firmware 56. I am looking for 59 but cant find.
Please send the link to download

**Comment by Trevelopment** [comment]
https://my.hidrive.com/share/hsodpqja.l#$/Mazda_Firmware/z%20Develop%20Firmware/Outdated%20Firmware
