### ISSUE TITLE
Can't compile using instructions in Wiki tab

### ISSUE THREAD

**Issue by RobsonMi** [gartnera/headunit#178]
I wanted to test out latest commits from today as they might solve some issues for me but I can't get it to work. First issue is libdbusxx is not found. Then despite that 'make' command runs and returns no errors. Newly created headunit file is 24MB though. Instead around 5-6 MB like for v 1.12. Also when installed in mazda it fails to start without error. Just hands whole infotainment screen.

Any updated instructions for building headunit binary?

**Comment by morpheus133** [comment]
Hi!
Use ubuntu 16.04!
And the following commands are needed to build it for headunit:
`apt-get update`
`apt-get install -y git zip ibsdl2-2.0-0 libsdl2-ttf-2.0-0 libportaudio2 libpng12-0 gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-alsa`

`git clone --recurse-submodules  https://github.com/gartnera/headunit.git`
If you want to build it for Headunit you need to go to mazda directory:
`cd /headunit/mazda/`

`make clean release`
And the result will be something like AndroidAuto_v1.05-52-g54b38d6.zip

It is larger than the offical one ~24mb but working on the headunit.

**Comment by RobsonMi** [comment]
On apt-get install line I get error:
Setting up unzip (6.0-20ubuntu1) ...
Setting up zip (3.0-11) ...
Errors were encountered while processing:
 blueman
E: Sub-process /usr/bin/dpkg returned an error code (1)

And then I get:
cp: preserving times for 'installer/config/androidauto/data_persist/dev/bin/headunit': Operation not permitted
cp: preserving times for 'installer/config/androidauto/data_persist/dev/bin/headunit.json': Operation not permitted
Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1

At the end of `make clean release` command. I am using Ubuntu 16.04 in WSL like suggested on wiki.

**Comment by ixnewton** [comment]
The compile platform I have used successfully is using the recommended Ubuntu 16.04 in a virtual machine (Virtualbox) with the suggested dependencies. Trying under my native Manjaro (Arch) proved too difficult to satisfy dependencies as libraries are mostly too recent. I have produced executable headunit builds which also weigh in at 22-23 Mb or so with this setup. 

To install I just copy the headunit file to /config/androidauto/data_persist/dev/bin/ folder on an existing USB install drive.

**Comment by RobsonMi** [comment]
> The compile platform I have used successfully is using the recommended Ubuntu 16.04 in a virtual machine (Virtualbox) with the suggested dependencies. Trying under my native Manjaro (Arch) proved too difficult to satisfy dependencies as libraries are mostly too recent. I have produced executable headunit builds which also weigh in at 22-23 Mb or so with this setup.
> 
> To install I just copy the headunit file to /config/androidauto/data_persist/dev/bin/ folder on an existing USB install drive.

@morpheus133 method produces nice zip file that contains installer folder which contents need to be moved to USB. Going to test the build in a moment in a car.

**Comment by krogoth2k** [comment]
Can You share this build please?

**Comment by RobsonMi** [comment]
Here it is and solved recent issues for me: https://github.com/gartnera/headunit/issues/173#issuecomment-589630973

**Comment by RobsonMi** [comment]
I've took the liberty to update Wiki page to reflect new commands and some new trick like `explorer.exe .` to open ubuntu files on windows. Hope it's not a problem.

**Comment by morpheus133** [comment]
Hi!
With the current wiki version you can only build the version for Headunit. The Ubuntu version will not work. 
It will be more use full to create an Docker image what contains all librarys and can build all versions without any modification needed.


```
FROM ubuntu:16.04

RUN apt-get update
# Dependencies for mazda binary build
RUN apt-get install -y git zip ibsdl2-2.0-0 libsdl2-ttf-2.0-0 libportaudio2 libpng12-0 gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-alsa
# Dependencies for ubuntu binary build
RUN apt-get install -y libssl-dev libusb-1.0-0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libsdl1.2-dev libgtk-3-dev libudev-dev libunwind-dev libsdl2-dev libgstreamer-plugins-bad1.0-dev protobuf-compiler
```

create image:
`docker build . -t mazdabuilder`

than we can run docker container like this:
```
docker run -it \
--name mazdabuilder \
-v </location_of_checkedou_repo>:/headunit/ \
mazdabuilder:latest \
/bin/bash

```
than in the container:
```
cd /headunit/mazda/
make clean release
```
This will build the binary and create the zip what will be available in </location_of_checkedou_repo> dir.

But the ubuntu binary will be not ok because it not contains the library.
```
cd /headunit/ubuntu/
make clean
make
```
Currently I trying to figure out how to link them

**Comment by khanhvu161188** [comment]
> Hi!
> With the current wiki version you can only build the version for Headunit. The Ubuntu version will not work.
> It will be more use full to create an Docker image what contains all librarys and can build all versions without any modification needed.
> 
> ```
> FROM ubuntu:16.04
> 
> RUN apt-get update
> # Dependencies for mazda binary build
> RUN apt-get install -y git zip ibsdl2-2.0-0 libsdl2-ttf-2.0-0 libportaudio2 libpng12-0 gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-alsa
> # Dependencies for ubuntu binary build
> RUN apt-get install -y libssl-dev libusb-1.0-0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libsdl1.2-dev libgtk-3-dev libudev-dev libunwind-dev libsdl2-dev libgstreamer-plugins-bad1.0-dev protobuf-compiler
> ```
> 
> create image:
> `docker build . -t mazdabuilder`
> 
> than we can run docker container like this:
> 
> ```
> docker run -it \
> --name mazdabuilder \
> -v </location_of_checkedou_repo>:/headunit/ \
> mazdabuilder:latest \
> /bin/bash
> ```
> 
> than in the container:
> 
> ```
> cd /headunit/mazda/
> make clean release
> ```
> 
> This will build the binary and create the zip what will be available in </location_of_checkedou_repo> dir.
> 
> But the ubuntu binary will be not ok because it not contains the library.
> 
> ```
> cd /headunit/ubuntu/
> make clean
> make
> ```
> 
> Currently I trying to figure out how to link them

hi mate, any luck with you on compile and run with Ubuntu environment?
