### ISSUE TITLE
Installed New AA 1.12. No disolay

### ISSUE THREAD

**Issue by tekkkadan** [gartnera/headunit#179]
Hey, I just installed the latest version of AA that fixed the crash issues the app was having. Now my AA doesn't load on my car. When I plug the USB, it just flashes my screen and the apps on my phone crash. I tried a different build 1.05 that someone compiled as well, but no luck.

Any solutions for this? Kinda frustrating cause everything was working fine until the new Maps update.

**Comment by aserper** [comment]
How did you install it? You should prepare a regular 1.12 installation, copy it to the usb stick, Then download this: https://github.com/gartnera/headunit/files/4235978/AndroidAuto_v1.05-52-g54b38d6.zip and copy the whole config/androidauto folder over the 1.12 install on your usb

**Comment by tekkkadan** [comment]
> How did you install it? You should prepare a regular 1.12 installation, copy it to the usb stick, Then download this: https://github.com/gartnera/headunit/files/4235978/AndroidAuto_v1.05-52-g54b38d6.zip and copy the whole config/androidauto folder over the 1.12 install on your usb

Yup, that's what I did. It still didn't detect anything. Does this have something to do with my AA on the phone or my Google Play Services?

**Comment by aserper** [comment]
It happened to me to in the first time that I installed it. I just tried
the same thing again and rebooted both the CMU and my phone
