### ISSUE TITLE
V1.13 Installer Download

### ISSUE THREAD

**Issue by ryoncy** [gartnera/headunit#182]
@Trevelopment where can i download V1.13 installer zip pack?

**Comment by Trevelopment** [comment]
http://aa.mazdatweaks.win and I just uploaded it to the [release](/gartnera/headunit/releases/tag/1.13)

**Comment by ryoncy** [comment]
@Trevelopment Thanks.

**Comment by binhthanhng** [comment]
> http://aa.mazdatweaks.win and I just uploaded it to the [release](/gartnera/headunit/releases/tag/1.13)

Thanks alot
