### ISSUE TITLE
Android Auto with Speedometer installed causes rotary control problems

### ISSUE THREAD

**Issue by ixnewton** [gartnera/headunit#186]
I had both AA headunit (v1.12) and Speedometer installed and it seemed to play well together with only the occasional issues loosing USB audio. Now we have AA v5.3.501644-release and AA headunit (v1.13) there are issues losing the rotary control input some time after AA headunit launches. Exit and restart does not restore control. For music apps the steering wheel controls are also affected. There were also frequent crash/reboots when starting up the Mazda CMU. 

To find a fix I removed Speedometer and re-installed AA headunit (v1.13) which has so far resolved these issues. To simplify the install I also removed the "touch screen while moving" and unticked "disable car GPS" options before compile. These may or may not be significant.

This configuration seems to play well, it is not a great loss to loose the speedometer but would be nice to have. I'm not sure if a fix is worth spending too much time on unless the developers can go straight to the suspect code. I would suggest the Speedometer JS which probably listens for input? 

It may of course be out of memory issues again so it is a choice between Speedometer and AA. I chose AA as the essential app with all its media app access.

**Comment by ixnewton** [comment]
Re-added "touch screen while moving" as it is annoying to not have this functionality when using AA. The Mazda CMU seldom needs touch for any action. The rotary dial can do anything as expected. The rotary dial now remains solid in AA interface though for maps a default to zoom of the map would be much smarter, with click to switch to selecting screen items. A UX opportunity missed by the AA designers?

**Comment by Trevelopment** [comment]
Yuip you  can try this also https://www.mazda3revolution.com/threads/aa-v1-14b-tru_go-fw55-59-fw70-abarth124-spider-sound-touch-usb-s-beta.239375/

**Comment by ixnewton** [comment]
The version AA v1.14b Tru_go_fw55-59_Standard_view_00 seems to be the correct version for my CMU 56.00.513 EU. I've given it a couple of days to show up any issues. Nothing so far, no audio/USB hang-ups, no AA launch failures. The notable change is the resolution giving a better default AA view with smaller info panel and button bar. As a result the initial zoom is like 1 step zoomed out which is better and kind of resolves my comment above for map zoom.
