### ISSUE TITLE
Communication error 7

### ISSUE THREAD

**Issue by Scorcher7986** [gartnera/headunit#20]
Just installed the latest version (v0.92B) on my mazda 3 2015, running software version 56.00.100 4A N. 
Whenever the phone is plugged in and android auto opens, it comes up with "Communication error 7 - Your car's software did not pass Android Auto security checks. For Details and support, contact the manufacturer"
I've checked that the date and time on both the car and mazda are the same.
My phone is the Samsung Galaxy S7

**Comment by ssepil** [comment]
Same problem .

**Comment by ignabel** [comment]
You need to install v0.93 or later to prevent that problem

**Comment by Scorcher7986** [comment]
Seems to be fixed in the latest 0.94 version
