### ISSUE TITLE
Uninstaller?

### ISSUE THREAD

**Issue by ColonialProject** [gartnera/headunit#22]
I don't see a way to uninstall this anywhere. Does anybody know a way? Also, the reason I'm uninstalling it is because I want to install a newer version. Is there an easier way to get the new version?

**Comment by Teecoder300** [comment]
Android Auto is only compatible with version 55 you can crash your unit by
having it on a new version. So make sure to uninstall it completely or
install version new version which will wipe out AA.

**Comment by SkyrisBactera** [comment]
So your saying I can just use the USB install method and it won't mess
anything up, even though I already have an older version of Android Auto
installed?

**Comment by ColonialProject** [comment]
Also, I meant a new version of Android Auto, not the OS

**Comment by SkyrisBactera** [comment]
Also, I'm ColonialProject 😉

**Comment by ColonialProject** [comment]
Oops! I meant

**Comment by Teecoder300** [comment]
I'm an not saying anything but be cautious to the OP. Also I assumed OP was
talking about uninstall AA to upgrade to a newer Mazda software version.

I thought Android Auto, auto updates on the app on your phone? I could be
wrong though.

**Comment by ColonialProject** [comment]
*facepalm* I can't github....

**Comment by ColonialProject** [comment]
I meant the headunit app. There have been commits to *this* project, that I
want on my Mazda. I'm just wondering how I could update my Mazda's headunit
app.

**Comment by Teecoder300** [comment]
Okay. My bad. Maybe the person who made the software can tell us. I think
when you're Android Auto app updates on your phone the version on the car
updates also. I could be wrong.

**Comment by SkyrisBactera** [comment]
OK, I'm going to wait for further clarification.

**Comment by gartnera** [comment]
Yeah it was attached to the V0.91B release. https://github.com/gartnera/headunit/releases/tag/v0.91B

Side note, if you are trying to upgrade to v59 I would hold off. I just bricked my car today trying to upgrade.

**Comment by SkyrisBactera** [comment]
Thanks!

**Comment by Teecoder300** [comment]
Meaning the phone app update does not change the AA version on the car.
Darn thank you. Works 80% of the time and for a free service I don't mind
the little hick-ups.

Thank you.

**Comment by Teecoder300** [comment]
So to uninstall download the uninstaller zip put it on a USB then follow on screen instructions?

**Comment by Teecoder300** [comment]
With the new Android auto app using only the phone it's nice to go back to normal OS. I would keep Android auto on my headup unit but the Bluetooth phone issues is killing me
