### ISSUE TITLE
0.94 causes letterbox graphical corruption 

### ISSUE THREAD

**Issue by apeatling** [gartnera/headunit#24]
Example:

![img_1428](https://cloud.githubusercontent.com/assets/1464705/19206865/d7e9f04c-8ca0-11e6-9f8c-75208a5610ab.JPG)

This is in a 2016 CX-5 with 0.94 and CMU version 55.00.760A

**Comment by Teecoder300** [comment]
This happens to me when I switch from the rear view camera back to AA. It
happens for about half a second

**Comment by izacus** [comment]
Should probably rollback the letterboxing fix - the UI looks fine without it, AA is built to be stretched over the whole headunit anyway.

**Comment by izacus** [comment]
The new aspect ratio fix (which stretches image over borders top/bottom) works well and looks good, so this can be closed I think :)
