### ISSUE TITLE
Rotary Input

### ISSUE THREAD

**Issue by borconi** [gartnera/headunit#28]
Ok as promised on the main thread here is how you can get rotary input instead of touchscreen.

hu_aap.c the sd_buf should look like this
```
byte sd_buf2 []={0x00, 0x06, 
//Touch+input CHANNEL
//This commented line is touchscreen only, active line is rotary input: 0x0A, 0x0F, 0x08, 0x01, 0x22, 0x0B, 0x0A, 0x01, 0x54, 0x12, 0x06, 0x08, 0xA0, 0x06, 0x10, 0xE0, 0x03, 
0x0a, 0x12, 0x08, 0x01, 0x22, 0x0e, 0x0a, 0x0c, 0x01, 0x02, 0x04, 0x13, 0x14, 0x15, 0x16, 0x17, 0x54, 0x80, 0x80, 0x04,

// SENSOR CHANNEL
0x0A, 0x10, 0x08, 0x02, 0x12, 0x0C, 0x0A, 0x02, 0x08, 0x01, 0x0A, 0x02, 0x08, 0x0A, 0x0A, 0x02, 0x08, 0x0D,
//                       18,  12,     10,    2,    8,    1,  10,   2,     8,    10, 10,    2,    8,    13


// Video CHANNEL
0x0A, 0x15, 0x08, 0x03, 0x1A, 0x11, 0x08, 0x03, 0x22, 0x0D, 0x08, 0x01, 0x10, 0x02, 0x18, 0x00, 0x20, 0x00, 0x28, -96, 0x01, 0x30, 0x00, 
// MIC CHANNEL
0x0A, 4+4+7,0x08, AA_CH_MIC, 0x2A, 4+7, 0x08, 1,    0x12, 7,    0x08, -128, 0x7d, 0x10, 0x10, 0x18, 1,
// CAR DEFINITION
						
                        0x12, 4, 'E', 'm', 'i', 'l',//1, 'A', // Car Manuf          Part of "remembered car"
                        0x1A, 4, 'A', 'l', 'b', 'e',//1, 'B', // Car Model
                        0x22, 4, '2', '0', '1', '6',//1, 'C', // Car Year           Part of "remembered car"
                        0x2A, 4, '0', '0', '0', '1',//1, 'D', // Car Serial     Not Part of "remembered car" ??     (vehicleId=null)
                        0x30, 0,//0,      // driverPosition
						
                        0x3A, 4, 'E', 'm', 'i', 'l',//1, 'E', // HU  Make / Manuf
                        0x42, 4, 'H', 'U', '1', '5',//1, 'F', // HU  Model
                        0x4A, 4, 'S', 'W', 'B', '1',//1, 'G', // HU  SoftwareBuild
                        0x52, 4, 'S', 'W', 'V', '1',//1, 'H', // HU  SoftwareVersion
                        0x58, 0,//1,//1,//0,//1,       // ? bool (or int )    canPlayNativeMediaDuringVr
                        0x60, 0,//1,//0,//0,//1        // mHideProjectedClock     1 = True = Hide	*/	
						
//THE LAST 3 CHANNEL KEEP THEM HERE SO WE CAN EXCLUDE THEM IF NEED BE.
0x0A, 4+6+7, 0x08, AA_CH_AU2, 0x1A, 6+7, 0x08, 1,  0x10, 2, 0x1A, 7, 0x08, -128, 0x7d,         0x10, 0x10,   0x18, 1,
0x0A, 4+6+7, 0x08, AA_CH_AU1, 0x1A, 6+7, 0x08, 1,  0x10, 1, 0x1A, 7, 0x08, -128, 0x7d,         0x10, 0x10,   0x18, 1,
0x0A, 4+6+8, 0x08, AA_CH_AUD, 0x1A, 6+8, 0x08, 1,  0x10, 3, 0x1A, 8, 0x08, -128,   -9, 0x02,   0x10, 0x10,   0x18, 02,

};
```

Here comes the codes for buttons on rotary:
Enter:
WRITE: 80 01 08 c8 f9 80 fd ab 87 d3 c3 14 22 0a 0a 08 08 17 10 01 18 00 20 00 ;
WRITE: 80 01 08 90 c3 aa aa ac 87 d3 c3 14 22 0a 0a 08 08 17 10 00 18 00 20 00 ;

Simulates moving the rotary controller
Down:
WRITE: 80 01 08 e8 bb be ad de 87 d3 c3 14 22 0a 0a 08 08 14 10 01 18 00 20 00 ;
WRITE: 80 01 08 f8 93 d8 e9 de 87 d3 c3 14 22 0a 0a 08 08 14 10 00 18 00 20 00 ;

Right:
WRITE: 80 01 08 c0 c4 e5 86 ed 87 d3 c3 14 22 0a 0a 08 08 16 10 01 18 00 20 00 ;
WRITE: 80 01 08 c8 eb c3 bb ed 87 d3 c3 14 22 0a 0a 08 08 16 10 00 18 00 20 00 ;

Up:
WRITE: 80 01 08 a8 fc e1 de f8 87 d3 c3 14 22 0a 0a 08 08 13 10 01 18 00 20 00 ;
WRITE: 80 01 08 e8 fe db ba f9 87 d3 c3 14 22 0a 0a 08 08 13 10 00 18 00 20 00 ;

Left:
WRITE: 80 01 08 e8 f2 97 ab 86 88 d3 c3 14 22 0a 0a 08 08 15 10 01 18 00 20 00 ;
WRITE: 80 01 08 c8 dd d0 86 87 88 d3 c3 14 22 0a 0a 08 08 15 10 00 18 00 20 00 ;

Simulates pressing the side buttons available on some rotary controllers.
Soft right:
WRITE: 80 01 08 80 e6 80 f6 f6 88 d3 c3 14 22 0a 0a 08 08 02 10 01 18 00 20 00 ;
WRITE: 80 01 08 f0 b5 ec a2 f7 88 d3 c3 14 22 0a 0a 08 08 02 10 00 18 00 20 00 ;

Soft left:
WRITE: 80 01 08 80 f2 c7 a7 88 89 d3 c3 14 22 0a 0a 08 08 01 10 01 18 00 20 00 ;
WRITE: 80 01 08 f0 ef fc fc 88 89 d3 c3 14 22 0a 0a 08 08 01 10 00 18 00 20 00 ;

Simulates rotating the rotary controller left (counter-clockwise) or right (clockwise).

rotate left:
WRITE: 80 01 08 c8 e9 d6 bb 8a 8a d3 c3 14 22 0a 0a 08 08 15 10 01 18 00 20 00 ;
WRITE: 80 01 08 b0 c0 a6 88 8b 8a d3 c3 14 22 0a 0a 08 08 15 10 00 18 00 20 00 ;

Rotate right:
WRITE: 80 01 08 b0 b8 dd ed ce 8a d3 c3 14 22 0a 0a 08 08 04 10 01 18 00 20 00 ;
WRITE: 80 01 08 b0 d4 9e ee cf 8a d3 c3 14 22 0a 0a 08 08 04 10 00 18 00 20 00 ;

Simulates a fast spin of the rotary controller to the left (counter-clockwise) or right (clockwise).
Left:
WRITE: 80 01 08 c0 9b fb 8f 93 8b d3 c3 14 32 11 0a 0f 08 80 80 04 10 ff ff ff ff ff ff ff ff ff 01 ;
WRITE: 80 01 08 80 bc d0 e2 99 8b d3 c3 14 32 08 0a 06 08 80 80 04 10 01 ;

Right:
WRITE: 80 01 08 c8 a9 f2 87 b8 8b d3 c3 14 32 11 0a 0f 08 80 80 04 10 fb ff ff ff ff ff ff ff ff 01 ;
WRITE: 80 01 08 a0 c6 94 b3 be 8b d3 c3 14 32 08 0a 06 08 80 80 04 10 05 ;

**Comment by izacus** [comment]
Hmm, I tried incorporating those changes and the AA doesn't even start - I get a "Launch AA on headunit" green screen on the phone and the session never sets up. Is the init payload / channel order correct?

**Comment by izacus** [comment]
This is great - I have most of the implementation fixing the keycodes done (works well in Ubuntu), just need to figure out what the rotary button keycode is and test in the actual car.

**Comment by borconi** [comment]
Happy to hear that it's working. Do you want to try to incorporate the Bluetooth fix as well? (See issue 2), I will say for beginning maybe hardcode in your cars Bluetooth Mac address to the code, but I'm quite confident that will sort the Bluetooth issue for good.

**Comment by izacus** [comment]
That's the plan (and hopefully GPS as well).

Btw, it seems that in your post here the keycodes  for rotate right / left and left / right are the same (just different timestamps). I had to use ones from the original Ubuntu source to get it working properly, see `cd_leftturn` etc. here: https://github.com/izacus/headunit/blob/00aae5a3c3a69a228d5e1c2edb8e0b13e9f16cac/ubuntu/main.c#L545

**Comment by borconi** [comment]
It is possible, I only extracted them very quickly from desktop head unit
emulator without actually double checking each value so might have mixed
them up.

Besides Desktop Head Unit gives you some shift+left and shift+right
combination so it is possible that I mixed up the values, sorry about that.

If you still miss any of them let me know and I will do a slow and more
careful data extraction from the desktop head unit.

GPS will be a really nice touch.

Kind regards.
Emil Borconi-Szedressy

**Comment by lmagder** [comment]
This has been fixed in master AFAIK

**Comment by ignabel** [comment]
@izacus @lmagder  On the latest build 5ef71ea , rotation works perfect. But if push the Knob RIGHT it triggers the OK Google Mic input, just like the steering wheel voice button does. Is that the expected behavior?

**Comment by izacus** [comment]
Yeah, it's how Auto behaves - left will always open the menu on the left, while right will start a microphone (essentially selecting the mike icon on the right) if there's nowhere to go right to.

**Comment by ignabel** [comment]
Sounds very logic with that explanation. Thanks!
