### ISSUE TITLE
Clear Directions on how to uninstall

### ISSUE THREAD

**Issue by Teecoder300** [gartnera/headunit#29]
Thank you to everyone who spent a lot of time on this. It has been a really cool project. I'd like to uninstall AA from it. I know there is an install attached to version .91B but I just wanted clear instructions on how to do so without bricking my car. Are the below instructions correct? I'd like to keep the tweek that allows touchscreen use while driving. Would I need to remove that also? If so how?

1. Remove files from flash drive.
2. format to fat32.
3. extract uninstaller files to flash drive.
4. Connect flash drive to car 
5. follow instructions

After doing this if I upgrade my mazda software or factory reset it, could that brick my car still? 

Thank you!!

**Comment by mishaaq** [comment]
#47
