### ISSUE TITLE
Android Auto Auto Start Head Unit on Boot Up[Enhancement]

### ISSUE THREAD

**Issue by Jinmcx** [gartnera/headunit#4]
Android Auto Auto Start Head Unit on Boot Up[Enhancement]

**Comment by scottschapiro** [comment]
As an alternative, I use Trigger to automatically launch AA whenever my phone is connected via Bluetooth to my car. https://play.google.com/store/apps/details?id=com.jwsoft.nfcactionlauncher

**Comment by Jinmcx** [comment]
I'm going to rename the title but I'm talking about Auto Start Android Auto on the head unit. You don't need the AA to a automatically launch in the car... it already does that

**Comment by scottschapiro** [comment]
Ah, my mistake. i didn't realize that AA launches automatically when connected to the car.

**Comment by lmagder** [comment]
This is implemented in main. Will be in the next release.
