### ISSUE TITLE
Headunit won't build for car anymore - missing libudev.h

### ISSUE THREAD

**Issue by izacus** [gartnera/headunit#42]
PR #37 added dependency on libudev, but failed to update m3-toolchain with it. So now a binary for Mazda cannot be built anymore, because the toolchain is missing libudev:

```In file included from ../hu/hu_aad.cpp:7:0:
../hu/hu_uti.h:26:21: fatal error: libudev.h: File or directory doesn't exist
 #include <libudev.h>
                     ^
compilation terminated.
Makefile:60: recipe for target '../hu/hu_aad.arm.o' failed
make: *** [../hu/hu_aad.arm.o] Error 1
``` 

Toolchain must be updated with proper libraries or dependency to them removed.

**Comment by lmagder** [comment]
Whoops, I need to test better :smile:  I will update the toolchain to add the libudev headers

**Comment by izacus** [comment]
Thanks! :D

(Working on Bluetooth service stuff and need to test on the car ;) )

**Comment by lmagder** [comment]
Great! Ok I think it's fixed
