### ISSUE TITLE
Share Audio Channel with Bluetooth & Android Auto

### ISSUE THREAD

**Issue by Jinmcx** [gartnera/headunit#44]
Is it possible to make AA share audio with the same channel as bluetooth (even if it's on a different device). Similar to .93 where they both use the same channel. I use two devices, one for android auto and one for bluetooth audio. I play music on my bluetooth audio such youtube and what not and it's not an option in android auto plus they blank the screen and you can't select your alternative music player. 

Would be great with this is an option otherwise I be stick with .93 =[.

**Comment by lmagder** [comment]
I think this will hopefully be supported in the next release with the new audio handling system.

**Comment by Jinmcx** [comment]
Awesome! I know this is a very useful feature so a person music isn't completely limited to android auto channel itself.

**Comment by mishaaq** [comment]
Just to reference: commit d0706eab21dbac9fca2ca3c967ded59e9faf1da6 fixes the issue.

**Comment by Jinmcx** [comment]
Wow that's so quick. Just curious, how do I test the latest AA version? Typically I use the "latest" release version but now it seems like I have to go through AIO? i never know what version/changes are in the AIO.

I forgot to add the other version i like the share channel it's cause it allows me to use my phone (be on my call) and use android auto. The trick I been using (works on .93) is make a phone call and while on call use turn on android auto and the phone won't disconnect (I didn't test it on the latest AIO i assume it didn't work because the bluetooth audio didn't even go through).

**Comment by Jinmcx** [comment]
Just wanted to report back with AA_master

I had an error that says headunit can't be launch but even with the error it works! the music button pulls up Music in AA which is cool but AA audio isn't share with the other channel like bluetooth (like .93) but I it's a good solution. Also the AA seems to never "kill itself". (can't pull the phone call work around in which I call then turn on AA usually I go to return to mazda and it kills AA). Also it's impossible to get audio back to AA.  It's getting very close =]!

**Comment by lmagder** [comment]
Good to hear it mostly working, @Jinmcx I think the other issues cover the those problems so I will close this one. Still trying to hammer out the last few messed up things.
