### ISSUE TITLE
Problem with Nexus 5

### ISSUE THREAD

**Issue by momico76** [gartnera/headunit#5]
Hi,
I tried several times to make the connection work with my Nexus 5 but I didn't succeed.  Curiously it worked fine with the 0.83 version. Now after connecting the device with the CMD via usb, the car screen freezes on a black screen and tries to restablish the connection several times (like in a boot-loop), without success and eventually, when I disconnect the cable, it returns an error about vendor id.
Maybe in the newer versions of AA the Nexus 5 vendor id is missing ? If that's the bug, could you please fix it?
My phone runs android 6.0.1, the AA app on the phone is the latest release and the cmd of my CX5 is the latest available .513EU.

Thanks in advance for your attention

Mark

**Comment by Jinmcx** [comment]
Which version are you using right now? I have Nexus 5 it works just fine. Both CM 13 and Stock. 
M2, .753, AA 91.B With Patch.

**Comment by momico76** [comment]
Mazda CX-5 2016, Nexus 5 with 6.0.1 build not rooted with AA app v. 1.6.281030 (2825091 release), AA 91.A on MZD 56.513EU...

**Comment by zeekthescorn** [comment]
I am having the same issue I have a nexus 6p and it just boot loops and then gives this vendor id code
im running 6.0.1

**Comment by gartnera** [comment]
Have you patched/reverted google play services? That's the only way headunit is working right now?

**Comment by Jinmcx** [comment]
@zeekthescorn try with .93 =)
