### ISSUE TITLE
Audio stutter when viewing map

### ISSUE THREAD

**Issue by galjun** [gartnera/headunit#51]
When I turn on online radio in TuneIn and change window to google maps on headunit on , music is playing with smal pauses pr 'freezes' ( sorry for my English). When i open windows with radio or phone  - music is playing fine.
The pauses depend on scale of map. Bigger part of map on the display - shorter "freezes", smaller part of map on display - it is impossible to listen music in total. I tried AA posted by mishaaq in this issue https://github.com/gartnera/headunit/issues/40#issuecomment-277437758

On 0.93 it works fine.

**Comment by Jinmcx** [comment]
What version you using? Where you getting your version? I only see .93/.94

**Comment by galjun** [comment]
issue #40  https://github.com/gartnera/headunit/issues/40#issuecomment-277218957

**Comment by lmagder** [comment]
I think this is a known issue with audio stutter, it's almost 99% gone in HEAD but sometimes still happens for me once and while.

Which phone do you have? On my 6P it happens very infrequently, and with a Pixel it never happens even after 4+ hours. It seems to be something with the phone lagging, but obviously real AA handles this somehow.

I can increase the audio buffer size, but then that adds audio lag, however this isn't Guitar Hero, so maybe that's ok. 🤷‍♂️

**Comment by galjun** [comment]
HI,
I have figured out that map+radio works fine  when i take out sd-card with maps from her place.
if card is inserted, I listen stutters.

**Comment by viktorgino** [comment]
Should have been solved by https://github.com/gartnera/headunit/pull/46/commits/408160f69c7a36c5f0aac071b43f3b3080e84f64

I had the same experience before this commit

**Comment by mishaaq** [comment]
According to @galjun it is linked to not so powerful CMU, not the audio buffer size. @lmagder it is not a Guitar Hero for sure, but it might be preferable to hear nav guidance earlier that just after passing by the right turn :).

**Comment by y2jhotaru** [comment]
I have the same problem. I'll try to remove maps sd card as workaround to see if it works for me. In addition to the stutter in the sound, Voice directions are desynchronized with the automatic volume. What I mean is that commonly the music volume lowers to let hear the voice directions, but in my case, the voice directions plays at the same volume of the music so is difficult to understand, and about 4 or 5 seconds later the volume lowers. I'm using a Xperia Z5 Compact.
