### ISSUE TITLE
Android Auto Kicks back audio to bluetooth after command

### ISSUE THREAD

**Issue by Jinmcx** [gartnera/headunit#54]
I notice Android auto kicks back to FM just fine after google now or direction but it doesn't do that to bluetooth device. (i.e. if u use android auto on an android and an iphone on bluetooth all connected at the same time). The only way to get audio back to the iphone on bluetooth is to go -> home -> music -> and then go back to AA.

**Comment by lmagder** [comment]
which commit are you using? There is bug related to this in the recent build that was posted but it's fixed in HEAD. AFAIK we don't handle the different audio sources differently with respect to focus handling.

**Comment by Jinmcx** [comment]
I was using Test version: #40 #40 comment. I wish I knew how to make new commit lol I been testing people's uploads.

**Comment by lmagder** [comment]
If you are running Linux or using the "Bash for Windows 10" environment you can check out this git repo and build the code with "make install" in the mazda folder.

Just to verify if it's fixed here a build of the current head in git: 
[installer_5ef71ea8a23adbd59d1c4b78241942383da835c2.zip](https://github.com/gartnera/headunit/files/788399/installer_5ef71ea8a23adbd59d1c4b78241942383da835c2.zip)

The crazy number is the commit which is the id of the version in git: https://github.com/gartnera/headunit/commit/5ef71ea8a23adbd59d1c4b78241942383da835c2
you can see them all here
https://github.com/gartnera/headunit/commits/master

It's a way of keeping track which version is which between releases.

**Comment by Jinmcx** [comment]
@lmagder Thanks! I'll try it out and report back.

I have a request is there anyway to bake in the autostart script intoversion  .93? If I have that I would pretty much be set because everything else like command knob is just extra. I was looking at commits and it didn't seen so simple ><!

**Comment by lmagder** [comment]
Thanks for trying. Ok so it seems there is something special about BT audio. My untested theory is that maybe when the BT audio gets the focus back it's in a paused state waiting for the user to press play. (unlike radio which can't pause) Either we need to code in a special case for BT audio to send the unpause command or the way we are requesting audio focus needs some flag or something so that CMU knows to resume playback after.

**Comment by mishaaq** [comment]
I think we need to grab and analyse DBUS communication regarding phone calls. I'm not sure if there is a [dbus-monitor](https://dbus.freedesktop.org/doc/dbus-monitor.1.html) available in the system, but compiling it should not be a rocket science.

**Comment by borconi** [comment]
Night not be related but, in the last 2 weeks I spent the lots of time trying to convert a single board computer to a Bluetooth handsfree. One of the problems I faced is actually very similar to this.

I was using pulaeaudio+ofono and after a call, most of the times pulaeaudio did not resume the playback.

I ended up monitoring the dbus, after a call calling a small script which used Bluetoothctl to reconnect to the phone (for some reason the a2dp connection was lost) and then send a play command trough dbus+pulaeaudio and it works nicely.

In case the CMU does use ofono+pulaeaudio I can share the script with you (a modified version of monitor-ofono available in the ofono git)

**Comment by Jinmcx** [comment]
> Thanks for trying. Ok so it seems there is something special about BT audio. My untested theory is that maybe when the BT audio gets the focus back it's in a paused state waiting for the user to press play. (unlike radio which can't pause) Either we need to code in a special case for BT audio to send the unpause command or the way we are requesting audio focus needs some flag or something so that CMU knows to resume playback after.

> 

From what I observe that doesn't seen to be the case I recall going back to my phone and try hitting play music and it won't play. I had to go into that music app of the CMU and which seem like it was the only way. I forgot to report that I use an android phone as a bluetooth device and same observation.

**Comment by mishaaq** [comment]
In the logs attached by @ignabel in https://github.com/gartnera/headunit/issues/61#issuecomment-284200100 there are registered many streams releated to bluetooth:
```
Found stream BTHFALERT session id 15
Found stream BTHF session id 14
Found stream BTMUSIC session id 13
Found stream BTHFVOL session id 10
```
Maybe the AA releases the audio for `BTHFALERT` on incoming call (everything is fine until answering the call) but then acquires it once again instead of leaving it for `BTHF` stream (CMU changes to this one, but then AA requires USB).

**Comment by lmagder** [comment]
I'm 90% sure this is fixed with the recent audio focus handling changes, but please re-open if that's not the case.
