### ISSUE TITLE
LG G4 Support

### ISSUE THREAD

**Issue by mradsl14** [gartnera/headunit#6]
I am experiencing issues with my LG G4 running android 6.0. It doesn't seem to connect, the phone recognises android auto, but it keeps disconnecting. I have rolled back my google play services to the correct version as well. I'm testing on Mazda 2, running CMU 56.

**Comment by mradsl14** [comment]
I am running V0.92

**Comment by Jinmcx** [comment]
You should retitle to google play services support because it's a universal issue.

**Comment by mradsl14** [comment]
That is a seperate issue and ill create a new issue, but I did roll my version back and it still didnt work. Im just wandering if the dev needs to add support that's all for the LG G4, like with Oppo

**Comment by Jinmcx** [comment]
Did you try version 9.0.83? This has been working for majority of people. LG vendor has always been on the headunit. I use a LG G2/Nexus 5

**Comment by mradsl14** [comment]
I haven't, I tried version 8.4.89, will try that version and report back

**Comment by mradsl14** [comment]
I tired the version, these are images from the headunit

![whatsapp-image-20160627 3](https://cloud.githubusercontent.com/assets/6948312/16384818/bcc59c82-3c8a-11e6-9a3c-a2548b90ddb2.jpg)
![whatsapp-image-20160627 2](https://cloud.githubusercontent.com/assets/6948312/16384819/bccb5f1e-3c8a-11e6-8bed-aa1305d7ce48.jpg)
![whatsapp-image-20160627 1](https://cloud.githubusercontent.com/assets/6948312/16384820/bcd1153a-3c8a-11e6-9161-25810fc01812.jpg)
![whatsapp-image-20160627](https://cloud.githubusercontent.com/assets/6948312/16384821/bcd7aa8a-3c8a-11e6-8593-e2b3766b5799.jpg)

**Comment by Jinmcx** [comment]
Never got that error before, did you try a different usb cord? Put it on MTP mode

**Comment by mradsl14** [comment]
I did ;(

**Comment by Jinmcx** [comment]
I got a G2 it works fine, try .91B with the patch

**Comment by mradsl14** [comment]
How can i remove v0.92B

**Comment by Jinmcx** [comment]
Garthera has a remove AA there or just install it over. The alternative is use the all one tweak remover for AA on the M3R forum.

**Comment by mradsl14** [comment]
I checked with the version you recommended and still doesnt work, all that happens is my phone flashes and the android auto icon is visible but then it disconnects and reconnects over and over.

**Comment by chinlin0924** [comment]
mine has same issue as mradsl14, what is the better google play service and android auto version should I use in phone mobile side to test the android auto code in linux?

**Comment by chinlin0924** [comment]
Can anyone list what versions of android auto and google play service did you successfully connect to android auto with the code repository here (via android or ubuntu linux)?

my test phone environment:  
android os: android 6
android auto : 1.6.281949
google play service: 9.2.56

results: connection failed

**Comment by Jinmcx** [comment]
@chinlin0924 Try with .93 =]
