### ISSUE TITLE
Log display is broken

### ISSUE THREAD

**Issue by lmagder** [gartnera/headunit#62]
The code in [_androidautoApp.js](https://github.com/gartnera/headunit/blob/master/mazda/installer/config/androidauto/jci/gui/apps/_androidauto/js/_androidautoApp.js) should be reading the log file written to /tmp/mnt/data/headunit.log as reported by the status results but something isn't working.

**Comment by Trevelopment** [comment]
all you need to do is remove localhost #80

**Comment by Trevelopment** [comment]
I put an onclick handler on the textbox under the credits.  Tap that baby and in like 2-3 seconds you got your log displayed.
