### ISSUE TITLE
Stuck in Bootup logo

### ISSUE THREAD

**Issue by alxAgu** [gartnera/headunit#7]
Hi, I was trying to install this tweak and my mazda is stuck in the boot up logo. Can't do anything. Any ideas?

Thanks,

A.

**Comment by pi5** [comment]
@alxAgu What model and year? I ask so that other owners can be careful too until this gets fixed.

**Comment by alxAgu** [comment]
@pi5, Mazda3, 2014. I was too excited about finally getting AA and didn't pay attention to the big red bold messages in countless forums warning people not to flash this without taking some precautions :-(

**Comment by Jinmcx** [comment]
@alxAgu Did you ever manage to get this fixed?

**Comment by alxAgu** [comment]
@Jinmcx: No, I'm still waiting for a miracle. 

I've seen a lot of people with similar issues, but I noticed the other day that my unit is not actually rebooting constantly as others have reported, instead, mine boots up once (the USB flash drive seems to get mounted as the LED light in my usb stick flashes once) but gets stuck in the animated Mazda logo.

**Comment by udynaldana** [comment]
did you fix your problem?

**Comment by alxAgu** [comment]
@udynaldana I haven't and I fear I won't be able to. I'm hoping that someone with actual field experience in Mazda will come forward and detail the steps to take the unit down and re-flash everything.

**Comment by Snowness** [comment]
[Recovery_v1.zip](https://github.com/gartnera/headunit/files/715499/Recovery_v1.zip)

Extract this zip file to the root directory of a FAT32 based USB drive.

**Comment by lmagder** [comment]
Sorry about your car @alxAgu, you could try some of ideas on the forum. But I'm not sure this is a problem with the headunit code specifically.
