### ISSUE TITLE
black screen when phone is plugged in

### ISSUE THREAD

**Issue by bahlaha** [gartnera/headunit#72]
I have a Mazda CX5 2016, version 56.00.513 4A N, installed AA v1.02
followed all the instructions but the screen goes black when the phone is plugged in, unplugging the USB cable returns back to the credit. tried with couple of phones but all the same. Please help, thank you!

**Comment by deycks** [comment]
You need activate the debugger in the phone.
What version of android do you have?

**Comment by bahlaha** [comment]
thank you deycks, tried activate the debugger but no luck, andoid 6

**Comment by Trevelopment** [comment]
Try these things: 
1. put the car in and out of reverse while the black screen is up
2. play a video with the video player.  It will give you a memory error at first but tilt the command knob to the right to go to the next video.  try 2 or 3 beforee giving up if that doesnt work
3. reboot your system and keep the phone connected while you reboot

**Comment by whoteit** [comment]
I had the same issue (or at least very similar). Android Auto launches fine, but as soon as video focus is list, the screen goes black. I can still hear nav / music, but the screen stayed black. Repro steps are simple:

1. Start car
2. Android auto launches fine
3. Put car in reverse, backup camera starts
4. Put car in drive, focus goes to a black android auto screen.

I luckily found a workaround (that could maybe help the devs pinpoint the issue). It was the USB stick that had my music in USB slot 2. I removed it, everything works fine now. I can reproduce this 100% of the time.

**Comment by Trevelopment** [comment]
We did find already that having another USB with music or Nav SD card connected causes the black screen issue so I think we can call this issue resolved.

**Comment by lmagder** [comment]
Is this a duplicate bug? If not it might be useful to keep it open just for tracking and avoiding people reporting it again.

I think there may be a legit bug here with our USB handling code if it's broken by having additional USB devices plugged in. Sure, the workaround is easy: unplug them. But it might point to a deeper issue and plus it's not an unreasonable ask that it should work. 😄 

@whoteit Can you provide a log file from when the problem reproduces?

**Comment by Trevelopment** [comment]
Well @lmagder I found that when I get a black screen it is because gstreamer is hitting `[ERR] mem allocation failed!` error which I have encountered from the [VideoPlayer App](https://github.com/Trevelopment/Mazda-Videoplayer) caused by a shortage of memory usually from the Nav SD card.   If it is fixable I am very interested to know how you would accomplish that so I can maybe apply it to the VideoPlayer code (which is 99% JavaScript).
If you think it is something fixable from within AA then be my guest and reopen.  I am just trying to clean up some of these issues that are getting stale :fox_face:

**Comment by lmagder** [comment]
Hmm, no idea then. That error indicates that a native memory allocation inside gstreamer is failing, which probably means that it the OS is actually out of memory. Not sure what we can do about that, possibly nothing.

Issue cleanup appreciated 👍
