### ISSUE TITLE
Stuck on installing screen

### ISSUE THREAD

**Issue by davepro305** [gartnera/headunit#73]
I had v0.94 installed for a time. I uninstalled it correctly using AIO and tried installing 1.02. I'm stuck on "Android auto in installing..." for over an hour now. I beleive this is not normal.

**Comment by mishaaq** [comment]
Could you paste here contents of the log file? Should be created on USB key with installer.

**Comment by davepro305** [comment]
Installer started.
MYDIR = /tmp/mnt/sdb1
CMU version = 55.00.760A-NA
Check mount point ... OK
= POPUP: AA INSTALL SCRIPT Welcome to Android Auto installation script. Would you like to proceed? Proceed Abort
Disabling watchdog and remounting for write access ... SUCCESS
Check whether Android Auto is installed ... NO
Installing Android Auto.
= POPUP INFO: INSTALLING Android Auto is installing ...

**Comment by davepro305** [comment]
that's all of it

**Comment by davepro305** [comment]
I tried a different USB flash drive and it worked. No idea why. Thank you
