### ISSUE TITLE
AA Stuck displaying credits.

### ISSUE THREAD

**Issue by Boomer-AU** [gartnera/headunit#74]
I installed AA with the AIO 2.6.8. All tweaks have worked ok, except Android Auto. It launches and is stuck on the credit screen. When checking the install logs, the following looks like the culprit : "Android Auto not found in additionalApps.json"

Any ideas?
[AIO_log.txt](https://github.com/gartnera/headunit/files/1220237/AIO_log.txt)

**Comment by Boomer-AU** [comment]
I attempted a second installation of AA only, without success. Log files seem a bit happier but the same symptoms exist - AA starts and gets stuck on credits display.
 Latest log attached. 
[AIO_log.txt](https://github.com/gartnera/headunit/files/1220242/AIO_log.txt)

**Comment by Trevelopment** [comment]
Are you connecting your Android phone to the USB connection.  If you are not seeing an error message then the headunit process is running and you need to connect your phone.
