### ISSUE TITLE
Toyota port?

### ISSUE THREAD

**Issue by JIVS** [gartnera/headunit#77]
Hey just asking if anyone have thought of/is working on a port for toyota OEM headunits

Or in any case if it has been tried and its not possible

**Comment by anish-kunduru** [comment]
I was running 2.7.0 in my 2017 Yaris iA (Mazda2) without major issues. Occasionally, I'd have to reset the headunit and would have to go back in and manually select my ALC settings again.

I just upgraded to 2.8.1, and so far haven't noticed anything major. The only annoying thing is that if I have to reset the headunit, I lose all my radio presets. Win some, lose some, I guess. :)

Really, the only thing left (for me) would be the ability to use the car radio from within in AA and automatic wireless functionality. Note that the manual wireless functionality is borked for Pie (I'm running a Pixel 3 XL).

**Comment by Trevelopment** [comment]
OK cool well @anish-kunduru those are 2 other separate issues (#138)  but it sounds to me like this ones a closer
