### ISSUE TITLE
Lost video focus after rear view camera

### ISSUE THREAD

**Issue by Dreamescaper** [gartnera/headunit#91]
When I put my Mazda 3 gear to reverse (to have read view camera shown on screen), and then return back, in most cases video focus does not return to AA screen.
In some cases it actually does - if I started AA from Applications menu.

AA Version: 1.05

**Comment by Soukyuu** [comment]
On AA 1.07 and EU 56.x firmware, the video focus briefly drops to MZD UI, then switches to AA for me so far. AA start was initiated by connecting the phone. Still a bit "unclean" but better than not returning to AA at all
