### ISSUE TITLE
Pause audio playback on mute

### ISSUE THREAD

**Issue by djmandell** [gartnera/headunit#98]
I have a Mazda3.  Right now if I'm listening to a podcast and I hit the mute button playback continues without sound.  It would be nice (and probably should be expected behavior) for playback to pause when the mute button is pressed.  There's a nice little hack for Mazda's internal player that allows for pausing the audio on mute, it would be great if this functionality could be extended to Android Audio as well.  

Let me know if this enhancement request needs to be formatted differently or if I've left out any useful information.

**Comment by aidandj** [comment]
Did a bit of digging on this, and the mute button isn't passed to android auto like the other multicontroller buttons are. So something would have to be handled differently.

**Comment by Trevelopment** [comment]
Also let me add that the native GUI is very context dependent meaning that if common does not have the command set as a global command then it can only be used when the app context that is currently running.  This is also why it is not possible to pause-on-mute USB audio when you are outside of the Entertainment context.  There are some ways to get around this by calling the app instance in framework using framework.getAppInstance() and making the command using the instance object but this does not work most of the time.
