### ISSUE TITLE
GPS Fix

### ISSUE THREAD

**Issue by FREESCALE009** [gartnera/headunit#99]
Hi. I would like to contribute to GPS issue as posted in Mazda forums. I believe i have a solution to the problem. If i am to post my code modification, should i post it here ?

**Comment by mishaaq** [comment]
Yes, you should create a Pull Request here.

**Comment by FREESCALE009** [comment]
Uhm that part i have not tried yet specifically using  commits on the repository.

My current state is;

1. did a git clone of the main branch using my Ubuntu box.
2. copied the m3-tool chain files to the m3-toolchain directory
3. modified the files related to the gps code
4. compiled the codes and upload the headunit binary to the car via scp
5. tested Android Auto and it seems to be working and stable with car GPS data

and i dont know how to share the modifications from this point :D  -> Github usage skils: 5% only

Teach me please.

**Comment by mishaaq** [comment]
Did you fork the project before or clone garnera/headunit directly?

**Comment by FREESCALE009** [comment]
Ok, i did the fork, made a local copy via clone, implement my changes and commit/published those changes on the forked copy. Modified 3 files plus the Makefile

https://github.com/FREESCALE009/headunit/commit/57c350e1ea4316d34165263ca237bd2aecfcc2b1

mazda/main.cpp -- to accommodate a new thread for the gps processing routines
mazda/gps/mzd_gps.cpp -- deleted the old gps routines and replaced it with the stable one
mazda/gps/mzd_gps.h --  mades some modifications to accommodate changes on the mzd_gps.cpp

the change was from /dev/ttyxxxx gps read to a dbus gps data read

mazda/Makefile is also edited to prevent mazda/gps/nematode/* from being compiled as they are not needed. Compile flags were temporarily changed to remove debugging info resulting to a smaller binary file

I did not issue a pull request yet as the edit on the Makefile is just temporary

**Comment by Trevelopment** [comment]
make another branch without the makefile changes then issue the PR

**Comment by FREESCALE009** [comment]
step by step please. I am just learning github :)

**Comment by FREESCALE009** [comment]
PR issued --

https://github.com/gartnera/headunit/pull/100

**Comment by Trevelopment** [comment]
fixed by #100

**Comment by lmagder** [comment]
Merged so closing.
